package no.fjordkraft.im.util;

/**
 * Created by bhavi on 5/11/2017.
 */
public interface IMConstants {

    String BASE_DESTINATION_FOLDER_PATH = "base.destination.dir";
    String GENERATED_PDF_FOLDER_NAME = "generated.pdf.folder.name";
    String BIRT_ENGINE_LOG_PATH = "birt.log.path";
    String PROCESSED_XML_FOLDER_NAME = "processedxml.folder.name";
    String CUSTOM_FONT_PATH="fjordkraft.custom.fonts.path";
    String NUM_OF_THREAD_FILESPLITTER ="num.thread.file.splitter";
    String NUM_OF_THREAD_PREPROCESSOR ="num.thread.preprocess";
    String NUM_OF_THREAD_PDFGENERATOR ="num.thread.pdf.generator";
    String MAX_QUEUE_CAPACITY="500";
    String BIRT_RPTDESIGN_PATH = "birt.layout.file.path";
    String SAMPLE_STATEMENT_FILE_PATH = "sample.statement.file.path";
    String SAMPLE_CAMPAIGN_IMAGE_PATH = "sample.campaign.image.path";
    static final String NETT = "NETT";
    static final String KRAFT = "Kraft";
    static final String RABATTER = "rabatter";
    static final String DIVERSE = "diverse";
    static final String NETTLEIE = "Nettleie";
    static final String STROM = "Strøm";
    static final char TRUE = '1';
    static final char FALSE = '0';
    static final String BARCODE_PREFIX = "2";
    static final int NEGATIVE = -1;
    static final String EMPTY_STRING = "";
    static final String TOTAL = "TOTAL";
    static final String STATUS_BY_CITY = "STATUS_BY_CITY";
    static final String STATUS_BY_BRAND = "STATUS_BY_BRAND";
    static final String CONTROL_FILE_PATH = "control.file.dir";
    static final String CONTROL_FILE_NAME = "control.file.name";
    static final String INVOICE_PDF = "INVOICE_PDF";
    static final String ATTACH_PDF = "ATTACH_PDF";
    static final String CAMPAIGN_FILE_PATH = "campaign.file.path";
    static final String BIRT_RESOURCE_PATH = "birt.resource.path";
    static final String STATEMENTS = "STATEMENTS";
    static final String NOT_APPLICABLE = "NA";
    static final String FKAS = "FKAS";
    static final String TKAS = "TKAS";
    static final String BRAND = "Brand";
    static final String GRID = "Grid";
    static final String CONFIG = "config";
    static final int ZERO = 0;
    static final int ONE = 1;
    static final int GREATER = 1;
    static final int LESSER = -1;
    static final String STRING = "STRING";
    static final String INTEGER = "INTEGER";
    static final String FLOAT = "FLOAT";
    static final String EQUALS = "EQUALS";
    static final String NOT_EQUALS = "NOT EQUALS";
    static final String GREATER_THAN = "GREATER THAN";
    static final String LESS_THAN = "LESS THAN";
    static final String GREATER_THAN_EQUAL_TO = "GREATER THAN EQUAL TO";
    static final String LESS_THAN_EQUAL_TO = "LESS THAN EQUAL TO";
    static final String ERROR = "ERROR";
    static final String WARNING = "WARNING";
    static final String STATEMENT = "STATEMENT";
    static final String SYSTEM_BATCH_FILE = "SYSTEM_BATCH_FILE";
    static final String YES = "YES";
    static final String NO = "NO";
    static final String UNDEFINED = "Undefined";
    static final String DIRECT_DEBIT = "DirectDebit";
    static final String GRANTED = "Granted";
    static final String CANCELLED = "Cancelled";
    static final String INTERNALLY_GRANTED = "InternallyGranted";
    static final String SYSTEM = "SYSTEM";
    static final String CAMPAIGN_IMAGE = "CAMPAIGN_IMAGE";
    static final String SUCCESS = "SUCCESS";
    static final String AUDIT_LOG = "AUDIT_LOG";
    static final String EMUXML = "EMUXML";
    static final String PDFE2B = "PDFE2B";
    static final String PDFEHF = "PDFEHF";
    static final String AFI_TRANSFER_FILE_AUTO_PICK = "afi.transfer.file.auto.pick";
    static final String PROCESSED_STATEMENT_XML_FILE_NAME="processed_statement.xml";
    static final String NUM_OF_STMT_PDF_GEN="num.statement.pdf.generation";
    static final String USE_KAFKA_PDF_PROCESSING="use.kafka.pdf.processing";
    static final String DELETE_GENERATED_FILES="delete.generated.files";
}
