server:
  port: 8888

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: bhavik
    password: bhavik123

logging:
  level:
    org.springframework.web: ERROR
    no.fjordkraft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /opt/app/invoice_manager/logs/application.log

if320.skip.bytes: true
base.directory.path: /opt/app/invoice_manager/if320-samples