server:
  port: 8888

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@imdb.cg8njogholnt.eu-central-1.rds.amazonaws.com:1521:orcl
    username: miles
    password: miles123

logging:
  level:
    org.springframework.web: ERROR
    no.fjordkraft: DEBUG
    #org.hibernate.type: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /opt/app/logs/application.log


if320.skip.bytes: true


liquibase:
  context: aws
  enabled: disable