server:
  port: 8888

logging:
  level:
    org.springframework.web: ERROR
    no.fjordkraft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /opt/app/invoice_manager/logs/application.log