--liquibase formatted sql

--changeset bhavik:1 context:prod
Insert into IM_BRAND_CONFIG (ID,BRAND,USE_EA_BARCODE,AGREEMENT_NUMBER,SERVICELEVEL,PREFIX_KID,KONTONUMMER,DESCRIPTION,POSTCODE,CITY,NATIONALID,REGION) values (1,'FKAS','1','0700','0','000','15031934610',null,null,null,null,null);


--changeset bhavik:2 context:prod
Insert into IM_CONFIG (NAME,VALUE) values ('base.destination.dir','/home/miles2/app/prod/im/output/');
Insert into IM_CONFIG (NAME,VALUE) values ('birt.log.path','/var/log/im-pdfgenerator/birt/');
Insert into IM_CONFIG (NAME,VALUE) values ('fjordkraft.custom.fonts.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/font');
Insert into IM_CONFIG (NAME,VALUE) values ('num.thread.preprocess','300');
Insert into IM_CONFIG (NAME,VALUE) values ('num.thread.pdf.generator','4');
Insert into IM_CONFIG (NAME,VALUE) values ('num.thread.file.splitter','1');
Insert into IM_CONFIG (NAME,VALUE) values ('birt.layout.file.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/Layout');
Insert into IM_CONFIG (NAME,VALUE) values ('control.file.dir','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/controlfiles');
Insert into IM_CONFIG (NAME,VALUE) values ('control.file.name','TKAS_p_304.pdf');
Insert into IM_CONFIG (NAME,VALUE) values ('campaign.file.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/Layout/FKAS_p_68.jpg');
Insert into IM_CONFIG (NAME,VALUE) values ('birt.resource.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/Layout');
Insert into IM_CONFIG (NAME,VALUE) values ('save.layout.encoding','UTF-8');
Insert into IM_CONFIG (NAME,VALUE) values ('layout.encoding','UTF-8');
Insert into IM_CONFIG (NAME,VALUE) values ('sample.statement.file.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/sampleFile/statement.xml');
Insert into IM_CONFIG (NAME,VALUE) values ('afi.transfer.file.auto.pick','YES');
Insert into IM_CONFIG (NAME,VALUE) values ('num.statement.pdf.generation','150');
Insert into IM_CONFIG (NAME,VALUE) values ('sample.campaign.image.path','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/sampleFile/FKAS_p_31.jpg');
Insert into IM_CONFIG (NAME,VALUE) values ('use.kafka.pdf.processing','false');
Insert into IM_CONFIG (NAME,VALUE) values ('delete.generated.files','false');

--changeset bhavik:3 context:prod,dev
Insert into IM_TRANSACTION_GROUP (ID,NAME,BRAND,TYPE,DESCRIPTION) values (1,'Diverse','FKAS',null,null);
Insert into IM_TRANSACTION_GROUP (ID,NAME,BRAND,TYPE,DESCRIPTION) values (2,'Rabatter','FKAS',null,null);


--changeset bhavik:4 context:prod,dev
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (1,'AGDER ENERGI NETT AS','info@agder.no','38607272','AGDER ENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (2,'ALTA KRAFTLAG A/L',null,'78450900','Alta Kraftlag A/L');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (3,'ANDØY ENERGI AS',null,'76115500','Andøy Energi AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (4,'ASKØY ENERGI AS','info@askoy.no','21492506','ASKØY ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (5,'ENERGI1 FOLLO RØYKEN AS','energi@no.no','21492506','ENERGI1 FOLLO RØYKEN AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (6,'FREDRIKSTAD ENERGI NETT','info@fred.no','21492506','FREDRIKSTAD ENERGI NETT');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (7,'AURLAND ENERGIVERK AS','info@aur.no','57632080','AURLAND ENERGIVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (8,'AUSTEVOLL KRAFTLAG SA',null,'55080000','AUSTEVOLL KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (9,'BALLANGEN ENERGI AS',null,'76926000','BALLANGEN ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (10,'BINDAL KRAFTLAG SA',null,'75031900','BINDAL KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (11,'BKK NETT AS','info@bkk.no','55127000','BKK NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (12,'DALANE ENERGI AS',null,'51462500','DALANE ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (13,'DRANGEDAL EVERK KF',null,'35997000','DRANGEDAL EVERK KF');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (14,'EIDEFOSS AS','eide@eide.no','61238200','EIDEFOSS AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (15,'EIDSIVA ENERGINETT AS','info@eidsiva.no','61286650','EIDSIVA ENERGINETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (16,'ETNE ELEKTRISITETSLAG SA',null,'53771155','ETNE ELEKTRISITETSLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (17,'FINNÅS KRAFTLAG SA',null,'53428900','FINNÅS KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (18,'FITJAR KRAFTLAG SA',null,'53457600','FITJAR KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (19,'FJELBERG KRAFTLAG SA',null,'53483000','FJELBERG KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (20,'FLESBERG ELEKTRISITETSVERK AS',null,'32760700','FLESBERG ELEKTRISITETSVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (21,'FORSAND ELVERK',null,'51700150','FORSAND ELVERK');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (22,'FOSEN NETT AS',null,'72529673','FOSEN NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (23,'FUSA KRAFTLAG SA',null,'56580020','FUSA KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (24,'GAULDAL NETT AS',null,'72438035','GAULDAL NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (26,'GLITRE ENERGI NETT AS - DISTRIBUSJON','info@glitre.no','31023000','GLITRE ENERGI NETT AS - DISTRIBUSJON');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (27,'GUDBRANDSDAL ENERGI NETT AS',null,'61294666','GUDBRANDSDAL ENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (28,'HAFSLUND NETT AS',null,'21490300','HAFSLUND NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (30,'HALLINGDAL KRAFTNETT AS',null,'32087100','HALLINGDAL KRAFTNETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (31,'HAMMERFEST ENERGI NETT AS',null,'78428200','HAMMERFEST ENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (32,'HARDANGER ENERGI AS',null,'53671600','HARDANGER ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (33,'HAUGALAND KRAFT NETT AS',null,'98705271','HAUGALAND KRAFT NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (34,'HELGELAND KRAFT AS',null,'75100000','HELGELAND KRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (35,'HEMNE KRAFTLAG SA',null,'72450100','HEMNE KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (36,'HEMSEDAL ENERGI KF',null,'31408888','HEMSEDAL ENERGI KF');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (37,'HERØYA NETT AS',null,'35926502','HERØYA NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (38,'HURUM NETT AS',null,'32792020','HURUM NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (39,'HØLAND OG SETSKOG EL VERK',null,'63854700','HØLAND OG SETSKOG EL VERK');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (40,'HÅLOGALAND KRAFT NETT AS',null,'77042500','HÅLOGALAND KRAFT NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (41,'INFOPARK AS',null,'71213600','INFOPARK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (43,'JÆREN EVERK',null,'51799500','JÆREN EVERK');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (44,'KLEPP ENERGI AS',null,'51789400','KLEPP ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (45,'KRAGERØ ENERGI AS',null,'35499966','KRAGERØ ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (46,'KRØDSHERAD EVERK',null,'32149450','KRØDSHERAD EVERK');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (47,'KVAM KRAFTVERK AS',null,'56553300','KVAM KRAFTVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (48,'KVIKNE-RENNEBU KRAFTLAG SA',null,'72428000','KVIKNE-RENNEBU KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (49,'KVINNHERAD ENERGI AS',null,'53475600','KVINNHERAD ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (50,'LOFOTKRAFT AS',null,'76067606','LOFOTKRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (51,'LUOSTEJOK KRAFTLAG SA',null,'78460600','LUOSTEJOK KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (52,'LUSTER ENERGIVERK AS',null,'57682917','LUSTER ENERGIVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (53,'LYSE ELNETT AS',null,'51908090','LYSE ELNETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (54,'LÆRDAL ENERGI AS',null,'57669400','LÆRDAL ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (55,'MELØY ENERGI AS',null,'75720190','MELØY ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (56,'MIDTKRAFT AS',null,'32783278','MIDTKRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (57,'MIDT-TELEMARK ENERGI AS',null,'35949000','MIDT-TELEMARK ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (58,'MØRENETT AS',null,'70050100','MØRENETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (59,'NESSET KRAFT AS',null,'71231600','NESSET KRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (60,'NORDKRAFT NETT AS',null,'76961175','NORDKRAFT NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (61,'NORDKYN KRAFTLAG SA',null,'78499700','NORDKYN KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (62,'NORDLANDSNETT AS',null,'75545110','NORDLANDSNETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (63,'NORDMØRE ENERGIVERK AS',null,'71565525','NORDMØRE ENERGIVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (64,'NORD-SALTEN KRAFT AS',null,'75771040','NORD-SALTEN KRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (65,'NORD-TRØNDELAG ELEKTRISITETSV','info@nte.no','74150740','NORD-TRØNDELAG ELEKTRISITETSV');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (68,'NORDVEST NETT AS',null,'70273500','NORDVEST NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (69,'NORD-ØSTERDAL KRAFTLAG SA',null,'62700700','NORD-ØSTERDAL KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (70,'NORE ENERGI AS',null,'32745069','NORE ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (71,'NOTODDEN ENERGI NETT AS',null,'32025050','NOTODDEN ENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (72,'ODDA ENERGI AS',null,'53650501','ODDA ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (73,'OPPDAL EVERK AS',null,'72400175','OPPDAL EVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (74,'ORKDAL ENERGI AS',null,'72466381','ORKDAL ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (75,'OSLOFJORD VARME AS',null,'67804960','OSLOFJORD VARME AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (76,'RAKKESTAD ENERGI AS',null,'69226500','RAKKESTAD ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (77,'RAULAND KRAFTFORSYNINGSLAG SA',null,'35062060','RAULAND KRAFTFORSYNINGSLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (78,'RAUMA ENERGI AS',null,'71226700','RAUMA ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (79,'REPVÅG KRAFTLAG SA',null,'78476800','REPVÅG KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (80,'RINGERIKS-KRAFT NETT AS',null,'32119650','RINGERIKS-KRAFT NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (81,'ROLLAG ELEKTRISITETSVERK SA',null,'32747750','ROLLAG ELEKTRISITETSVERK SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (82,'RØROS ELEKTRISITETSVERK AS',null,'72414810','RØROS ELEKTRISITETSVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (83,'SANDØY ENERGI AS',null,'71275600','SANDØY ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (84,'SFE NETT AS - GROV','info@sfe.no','57884850','SFE NETT AS - GROV');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (85,'SKAGERAK NETT AS',null,'35935000','SKAGERAK NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (86,'SKÅNEVIK ØLEN KRAFTLAG AS',null,'53771300','SKÅNEVIK ØLEN KRAFTLAG AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (87,'SOGNEKRAFT AS',null,'57698603','SOGNEKRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (88,'STANGE ENERGI NETT AS',null,'48236480','STANGE ENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (89,'STRANDA ENERGI AS',null,'93079890','STRANDA ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (90,'STRYN ENERGI AS',null,'57873600','STRYN ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (91,'SULDAL ELVERK KF',null,'52792602','SULDAL ELVERK KF');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (92,'SUNNDAL ENERGI KF',null,'71689570','SUNNDAL ENERGI KF');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (93,'SUNNFJORD ENERGIVERK','info@sunnfjord.com','57722310','SUNNFJORD ENERGIVERK');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (94,'SVORKA ENERGI AS',null,'97912222','SVORKA ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (95,'SYKKYLVEN ENERGI AS',null,'70246300','SYKKYLVEN ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (96,'TINN ENERGI AS',null,'35080900','TINN ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (97,'TROLLFJORD NETT AS',null,'76118020','TROLLFJORD NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (98,'TROMS KRAFT AS',null,'77601100','TROMS KRAFT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (99,'TRØGSTAD ELVERK AS',null,'69824950','TRØGSTAD ELVERK AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (100,'TRØNDERENERGI NETT AS',null,'73500050','TRØNDERENERGI NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (101,'TYSNES KRAFTLAG SA',null,'53430050','TYSNES KRAFTLAG SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (102,'UVDAL KRAFTFORSYNING SA',null,'32745000','UVDAL KRAFTFORSYNING SA');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (103,'VALDRES ENERGIVERK A/S','info@valdrs.no','61366101','VALDRES ENERGIVERK A/S');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (104,'VANG ENERGIVERK KF',null,'61367550','VANG ENERGIVERK KF');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (105,'VARANGER KRAFTNETT AS',null,'78962610','VARANGER KRAFTNETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (106,'VESTERÅLSKRAFT NETT AS',null,'7635','VESTERÅLSKRAFT NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (107,'VEST-TELEMARK KRAFTLAG AS',null,'35075700','VEST-TELEMARK KRAFTLAG AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (108,'VOKKS NETT AS',null,'61112798','VOKKS NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (109,'VOSS ENERGI AS',null,'56528380','VOSS ENERGI AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (110,'YMBER AS',null,'77770400','YMBER AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (111,'ØVRE EIKER NETT AS',null,'32251422','ØVRE EIKER NETT AS');
Insert into IM_GRID_CONFIG (ID,GRID_NAME,EMAIL,PHONE,GRID_LABEL) values (112,'ÅRDAL ENERGI KF',null,'57648600','ÅRDAL ENERGI KF');

--changeset bhavik:5 context:prod
Insert into IM_RULE_ATTRIBUTES (ID,NAME,TYPE,FIELD_MAPPING,OPTIONS) values (25,'Distribution Method','STRING','distributionMethod','EHF, NOT EHF');
Insert into IM_RULE_ATTRIBUTES (ID,NAME,TYPE,FIELD_MAPPING,OPTIONS) values (23,'Account Category','STRING','accountCategory.code','TPM, NOT TPM');
Insert into IM_RULE_ATTRIBUTES (ID,NAME,TYPE,FIELD_MAPPING,OPTIONS) values (26,'Credit Limit','INTEGER','creditLimit',null);
Insert into IM_RULE_ATTRIBUTES (ID,NAME,TYPE,FIELD_MAPPING,OPTIONS) values (22,'Legal Part Class','STRING','legalPartClass','Individual,Organization');
Insert into IM_RULE_ATTRIBUTES (ID,NAME,TYPE,FIELD_MAPPING,OPTIONS) values (1,'Pincode of area','STRING','postcode',null);

--changeset bhavik:6 context:prod,dev
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (1,'Credit','Fakturagebyr bedrift Kredit','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (2,'Credit','Fakturagebyr privat Kredit','DI;Rabatt: Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (3,'Credit','Flatgebyr 3 bet fri månad','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (4,'Credit','Flatgebyr Rabatt','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (5,'Credit','Jevn strømregning, tre månedene gratis','DI;Jevn strømregning, gratis tre første måneder');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (6,'Debit','Fakturagebyr bedrift','DI;Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (7,'Debit','Fakturagebyr privat','DI;Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (8,'Debit','Flatgebyr','DI;Full kontroll');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (9,'Debit','Flatgebyr bedrift','DI;Jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (10,'Debit','Flatgebyr med bet fri månad','DI;Full kontroll, betalingsfri måned');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (11,'Credit','DI;Korrigering purregebyr','DI;Korrigering purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (12,'Credit','DI;Rabatt Min Bedrift','DI;Rabatt Min Bedrift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (13,'Credit','EK; Rabatt 100% fornøyd','DI; Rabatt 100% fornøyd');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (14,'Credit','EK; Rabatt fakturagebyr','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (15,'Credit','EK; Rabatt Gratis Strøm','DI; Rabatt Gratis Strøm');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (16,'Credit','EK; Rabatt Min bedrift','DI; Rabatt Min bedrift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (17,'Credit','EK; Rabatt purregebyr','DI; Rabatt purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (19,'Credit','EK;Annen kompensasjon','DI;Annen kompensasjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (20,'Credit','EK;Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (21,'Credit','EK;Kompensasjon bruddgebyr','DI; Kompensasjon bruddgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (22,'Credit','EK;Kompensasjon forsinket oppstart','DI; Kompensasjon forsinket oppstart');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (23,'Credit','EK;kompensasjon Kundefordel','DI; kompensasjon Kundefordel');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (24,'Credit','EK;Korrigering av strømpris','DI;Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (25,'Credit','EK;Rabatt 100% Fornøyd','DI;Rabatt 100% Fornøyd');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (26,'Credit','EK;Rabatt forsinkelsesrente','DI;Rabatt forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (28,'Credit','EK;Rabatt Trippelgaranti','DI;Rabatt Trippelgaranti');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (29,'Credit','EK;Rabatt Trumf Kampanje','DI;Rabatt Trumf Kampanje');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (30,'Credit','Fakturagebyr bedrift Kredit CHARGE','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (31,'Credit','Fakturagebyr privat Kredit CHARGE','DI;Rabatt: Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (32,'Credit','Flatgebyr creditering','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (33,'Credit','Flatgebyr Rabatt CHARGE','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (34,'Credit','Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (35,'Credit','Gebyr rabatt','DI;Rabatt Jevn Strømregning mars-april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (37,'Credit','Kjøp av kraftproduksjon','DI;Kjøp av kraftproduksjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (38,'Credit','Korrigering Flatgebyr','DI;Jevn strømregning korringering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (39,'Credit','MVA','DI;DI;MVA - h?y sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (40,'Credit','Purregebyr Kredinor','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (41,'Credit','Rabatt Administrasjonsgebyr','DI;Rabatt Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (42,'Credit','Refusjon Purregebyr / Morarenter','DI;Refusjon Purregebyr / Morarenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (43,'Credit','Tilbakeføring purregebyr CHARGE','DI;Tilbakeføring purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (44,'Credit','Tilbakeføring renter CHARGE','DI;Tilbakeføring renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (45,'Credit','Øresavrundning','DI;Øresavrundning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (46,'Debit','Administrasjonsgebyr','DI;Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (47,'Debit','EK;Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (48,'Debit','Flatgebyr','DI;Jevn strømregning mars');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (49,'Debit','Flatgebyr','DI;Jevn strømregning april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (50,'Debit','Flatgebyr','DI;Jevn strømregning mars-april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (51,'Debit','FlatgebyrK','DI;Jevn strømregning K');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (52,'Debit','Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (53,'Debit','Garantert fornøyd Pluss','DI;Garantert fornøyd Pluss');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (54,'Debit','Korrigering av strømpris tilgodebeløp','DI; Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (55,'Debit','MVA','DI;DI;MVA - h?y sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (56,'Debit','Purregebyr','DI;Transaksjon fra påminnelse');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (57,'Debit','Purregebyr Kredinor','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (58,'Debit','Refusjon Purregebyr / Morarenter','DI;Refusjon Purregebyr / Morarenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (59,'Debit','Øresavrundning','DI;Øresavrundning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (60,'Debit','Purregebyr','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (62,'Credit','Omtvistet beløp','DI;Omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (64,'Debit','Omtvistet belöp','DI;Omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (65,'Debit','Tilbakefört omtvistet belöp','DI;Tilbakeført omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (69,'Credit','For mye innbetalt nettleie','DI;For mye innbetalt nettleie');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (70,'Credit','Overføring avbetalingskonto','DI;Avtalt beløp for avbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (71,'Credit','Overføring avbetalingskontoGA','DI;Overføring avbetalingskontoGA');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (72,'Credit','Overført grunnet feil innbetaling','DI;Overført innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (73,'Credit','Tilbakeføring purregebyr','DI;Tilbakeføring purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (74,'Credit','Tilbakeføring renter','DI;Tilbakeføring renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (75,'Credit','Tilbakeført Jevnstrømregning','DI;Tilbakeført Jevnstrømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (76,'Credit','Unspecified credit','DI;Overf¿¿rt tilgodebel¿¿p');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (77,'Debit','Administrajonsavgift','DI;Administrasjonsavgift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (78,'Debit','EK;Tilbakefore kompensasjon','DI;Tilbakefore kompensasjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (79,'Debit','For lite innbetalt nettleie','DI;For lite innbetalt nettleie');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (82,'Debit','Manuelt fakturagebyr','DI;Manuelt fakturagebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (83,'Debit','NedbetalingsordningGA','DI;Nedbetalingsordning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (84,'Debit','Negativ innbetaling','DI;Negativ innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (85,'Debit','Unspecified debit','DI;Overf¿¿rt skyldig bel¿¿p');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (86,'Debit','Ut grunnet feil innbetaling','DI;Korrigert innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (87,'Credit','Opprettelse av avbetalingslösning','DI;Opprettelse av avbetalingsløsning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (88,'Debit','Opprettelse av avbetalingslösning','DI;Opprettelse av avbetalingsløsning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (90,'Debit','Nedbetalingsordning','DI;Nedbetalingsordning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (91,'Credit','Renter tilgode','DI;Renter tilgode');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (92,'Debit','Avbetalingsrenter','DI;Avbetalingsrenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (94,'Debit','Overtrekksrenter','DI;Overtrekksrenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (95,'Debit','Skyldige renter','DI;Skyldige renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (96,'Credit','Intern kreditering','DI;Intern kreditering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (97,'Debit','Intern debitering','DI;Intern debitering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (98,'Debit','Fradragsberettiget rente','DI;Fradragsberettiget rente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (99,'Credit','Overföring','DI;Overføring til inkasso');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (100,'Credit','Overföring','DI;Overføring');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (101,'Debit','Overföring','DI;Overføring til inkasso');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (102,'Debit','Overföring','DI;Overføring');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (104,'Credit','Moms ekstern aktør','DI;Moms ekstern aktør');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (105,'Credit','MVA (avsetning tap)','DI;MVA (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (106,'Credit','MVA Credit','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (109,'Credit','MVA Flat - Credit','DI;MVA - Flat');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (110,'Credit','MVA Paper - Credit','DI;MVA - Paper');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (111,'Credit','MVA Rabatt Administrasjonsgebyr','DI;MVA Rabatt Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (112,'Debit','Moms ekstern aktør)','DI;Moms ekstern aktør');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (113,'Debit','MVA','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (116,'Debit','MVA Administrasjonsgebyr','DI;MVA Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (117,'Debit','MVA Flat','DI;MVA - Flat');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (118,'Debit','MVA Paper','DI;MVA - Paper');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (120,'Credit','MVA Netteier (avsetning tap) Credit','DI;MVA netteier (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (121,'Debit','MVA (avsetning tap)','DI;MVA (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (122,'Debit','MVA Netteier (avsetning tap)','DI;MVA netteier (avsetning tap)');



--changeset bhavik:7 context:prod,dev
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (1,1,54);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (2,1,77);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (3,1,46);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (4,1,6);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (5,1,92);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (6,1,55);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (7,1,79);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (8,1,47);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (9,1,52);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (10,1,98);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (11,1,8);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (12,1,10);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (13,1,53);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (14,1,97);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (15,1,9);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (16,1,51);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (17,1,49);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (18,1,48);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (19,1,50);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (20,1,86);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (21,1,121);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (22,1,117);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (23,1,118);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (24,1,113);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (25,1,116);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (26,1,122);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (27,1,82);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (28,1,112);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (29,1,90);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (30,1,83);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (31,1,84);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (32,1,64);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (33,1,88);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (34,1,85);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (35,1,102);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (36,1,101);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (37,1,94);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (38,1,7);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (39,1,60);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (40,1,57);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (41,1,58);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (42,1,95);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (43,1,78);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (44,1,65);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (45,1,56);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (46,1,59);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (48,2,21);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (49,2,22);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (50,2,13);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (51,2,15);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (52,2,16);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (53,2,17);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (54,2,23);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (55,2,19);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (56,2,70);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (57,2,39);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (58,2,69);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (59,2,20);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (60,2,34);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (61,2,96);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (62,2,38);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (63,2,5);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (64,2,37);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (65,2,11);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (66,2,24);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (67,2,105);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (68,2,109);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (69,2,110);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (70,2,106);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (71,2,111);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (72,2,120);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (73,2,104);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (74,2,62);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (75,2,87);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (76,2,76);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (77,2,100);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (78,2,71);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (79,2,99);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (80,2,72);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (81,2,40);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (82,2,25);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (83,2,41);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (84,2,14);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (85,2,1);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (86,2,30);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (87,2,35);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (88,2,12);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (89,2,28);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (90,2,29);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (91,2,26);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (92,2,3);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (93,2,4);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (94,2,33);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (95,2,32);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (96,2,2);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (97,2,31);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (98,2,42);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (99,2,91);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (100,2,73);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (101,2,43);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (102,2,74);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (103,2,44);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (104,2,75);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (105,2,45);


--changeset bhavik:8 context:prod
Insert into IM_CONFIG (NAME,VALUE) values ('base.path.campaign','/app-invoicemanager/invoice-manager/im-pdfgenerator/current/campaign/');
Insert into IM_CONFIG (NAME,VALUE) values ('read.campaign.image.filesystem','true');
Insert into IM_CONFIG (NAME,VALUE) values ('read.advt.pdf.filesystem','true');

