--liquibase formatted sql
--changeset arpita:1 context:prod,dev
---------------------Insert script for New BRAND : GEAS
Insert into IM_BRAND_CONFIG (ID,BRAND,USE_EA_BARCODE,AGREEMENT_NUMBER,SERVICELEVEL,PREFIX_KID,KONTONUMMER,DESCRIPTION,POSTCODE,CITY,NATIONALID,REGION,CREATE_TIME,UPDATE_TIME) values (10,'GEAS','0','0706','6','236','15038671925','Midt Energi AS','57',null,'7291','Stren',to_timestamp('22-OCT-18 01.47.02.438000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into IM_TRANSACTION_GROUP (ID,NAME,BRAND,TYPE,DESCRIPTION) values (9,'Diverse','GEAS',null,null);

--Adding New Transaction Categories for GEAS brand.
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (192,'Debit','MVA Credit Charge','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (193,'Debit','MVA Insurance Credit','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (194,'Debit','MVA Charge','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (195,'Debit','MVA Insurance','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (196,'Debit','MVA Netteier (avsetning tap) Credit','DI;MVA netteier (avsetning tap)');

Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (404,9,19);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (405,9,25);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (406,9,34);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (407,9,37);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (408,9,42);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (409,9,44);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (410,9,57);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (411,9,58);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (412,9,60);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (413,9,62);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (414,9,64);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (415,9,65);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (416,9,69);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (417,9,70);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (418,9,72);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (419,9,77);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (420,9,79);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (421,9,83);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (422,9,84);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (423,9,86);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (424,9,87);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (425,9,88);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (426,9,91);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (427,9,92);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (428,9,94);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (429,9,95);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (430,9,96);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (431,9,97);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (432,9,98);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (433,9,99);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (434,9,100);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (435,9,101);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (436,9,102);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (437,9,104);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (438,9,106);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (439,9,112);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (440,9,113);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (441,9,121);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (442,9,122);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (443,9,127);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (444,9,128);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (445,9,129);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (446,9,130);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (447,9,131);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (448,9,133);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (449,9,134);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (450,9,135);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (451,9,136);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (452,9,137);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (453,9,138);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (454,9,139);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (455,9,140);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (456,9,142);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (457,9,143);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (458,9,145);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (459,9,146);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (460,9,147);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (461,9,148);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (462,9,149);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (463,9,150);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (464,9,152);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (465,9,153);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (466,9,154);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (467,9,155);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (468,9,157);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (469,9,158);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (470,9,159);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (471,9,160);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (472,9,162);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (473,9,176);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (474,9,181);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (475,9,187);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (476,9,188);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (477,9,189);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (478,9,191);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (479,9,192);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (480,9,193);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (481,9,194);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (482,9,195);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (483,9,196);

---------------------Insert script for New BRAND : DKAS
Insert into IM_BRAND_CONFIG (ID,BRAND,USE_EA_BARCODE,AGREEMENT_NUMBER,SERVICELEVEL,PREFIX_KID,KONTONUMMER,DESCRIPTION,POSTCODE,CITY,NATIONALID,REGION,CREATE_TIME,UPDATE_TIME) values (11,'DKAS','0','0707','7','237','15038939251','Dragefossen Kraftanlegg AS','20','Osvegen 6 ','8251','Rognan',to_timestamp('22-OCT-18 01.51.32.295000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into IM_TRANSACTION_GROUP (ID,NAME,BRAND,TYPE,DESCRIPTION) values (10,'Diverse','DKAS',null,null);


Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (484,10,19);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (485,10,34);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (486,10,37);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (487,10,42);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (488,10,44);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (489,10,57);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (490,10,60);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (491,10,70);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (492,10,77);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (493,10,79);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (494,10,84);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (495,10,86);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (496,10,87);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (497,10,88);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (498,10,90);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (499,10,91);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (500,10,92);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (501,10,94);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (502,10,95);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (503,10,96);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (504,10,97);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (505,10,98);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (506,10,99);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (507,10,100);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (508,10,101);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (509,10,104);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (510,10,106);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (511,10,112);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (512,10,127);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (513,10,128);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (514,10,131);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (515,10,135);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (516,10,136);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (517,10,137);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (518,10,138);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (519,10,139);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (520,10,140);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (521,10,144);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (522,10,145);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (523,10,146);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (524,10,147);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (525,10,148);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (526,10,149);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (527,10,150);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (528,10,154);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (529,10,155);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (530,10,159);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (531,10,160);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (532,10,162);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (533,10,164);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (534,10,169);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (535,10,170);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (536,10,172);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (537,10,176);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (538,10,181);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (539,10,187);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (540,10,188);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (541,10,189);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (542,10,191);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (543,10,192);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (544,10,193);
Insert into IM_TRANSACTION_GRP_CATEGORY (ID,TG_ID,TC_ID) values (545,10,194);

--changeset arpita:2 context:dev

 CREATE TABLE IM_ACCOUNT_ATTACHMENT
   (ATTACHMENT_TYPE VARCHAR2(20 BYTE),
	BRAND VARCHAR2(20 BYTE),
	ATTACHMENT_CONFIG_TYP VARCHAR2(20 BYTE),
	ACCOUNT_ATTACHMENT_ID NUMBER NOT NULL ENABLE,
	CREATE_TIME TIMESTAMP (6),
	UPDATE_TIME TIMESTAMP (6),
	DESCRIPTION VARCHAR2(200 BYTE),
	CREATED_BY VARCHAR2(40 BYTE),
	FILE_TYPE VARCHAR2(20 BYTE),
	FILE_CONTENT CLOB,
	CONSTRAINT PK_ACC_ATTACHMENT PRIMARY KEY (ACCOUNT_ATTACHMENT_ID));

CREATE TABLE IM_ACCOUNT_ATTACHMENT_MAPPING
   (ID NUMBER,
    ACCOUNT_NO VARCHAR2(20),
	ACCOUNT_ATTACHMENT_ID NUMBER,
	CUSTOMER_ID VARCHAR2(20),
	CREATE_TIME TIMESTAMP (6),
    UPDATE_TIME TIMESTAMP (6),
	IS_ACTIVE CHAR(1),
	FILESTORED TIMESTAMP (6),
	CREATED_BY VARCHAR2(40),
    CONSTRAINT PK_ATTACHMENT_MAPPING PRIMARY KEY (ID));

 create sequence IM_ACCOUNT_ATCHMNT_MAP_SEQ
    start with 1
    increment by 1
    nocache
    nocycle;

 create sequence IM_ACCOUNT_ATTACHMENT_SEQ
     start with 1
     increment by 1
     nocache
     nocycle;


--changeset arpita:3 context:dev
CREATE TABLE "V_CUSTOMER_DETAILS"
  (	"ACCOUNTNO" VARCHAR2(20 BYTE),
    "GIRO_ENABLED" NUMBER(1,0)
  );



