//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FromDate"/>
 *         &lt;element ref="{}ToDate"/>
 *         &lt;element ref="{}StatementLine" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}StatementSummary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromDate",
    "toDate",
    "statementLine",
    "statementSummary"
})
@XmlRootElement(name = "AccountStatement")
public class AccountStatement {

    @XmlElement(name = "FromDate", required = true)
    protected String fromDate;
    @XmlElement(name = "ToDate", required = true)
    protected String toDate;
    @XmlElement(name = "StatementLine")
    protected List<StatementLine> statementLine;
    @XmlElement(name = "StatementSummary", required = true)
    protected StatementSummary statementSummary = new StatementSummary();

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(String value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(String value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the statementLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatementLine }
     * 
     * 
     */
    public List<StatementLine> getStatementLine() {
        if (statementLine == null) {
            statementLine = new ArrayList<StatementLine>();
        }
        return this.statementLine;
    }

    /**
     * Gets the value of the statementSummary property.
     * 
     * @return
     *     possible object is
     *     {@link StatementSummary }
     *     
     */
    public StatementSummary getStatementSummary() {
        return statementSummary;
    }

    /**
     * Sets the value of the statementSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatementSummary }
     *     
     */
    public void setStatementSummary(StatementSummary value) {
        this.statementSummary = value;
    }

}
