//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BranchCode"/>
 *         &lt;element ref="{}MICRCode"/>
 *         &lt;element ref="{}BranchDetail"/>
 *         &lt;element ref="{}PhoneNo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "branchCode",
    "micrCode",
    "branchDetail",
    "phoneNo"
})
@XmlRootElement(name = "Branch")
public class Branch {

    @XmlElement(name = "BranchCode")
    protected short branchCode;
    @XmlElement(name = "MICRCode")
    protected int micrCode;
    @XmlElement(name = "BranchDetail", required = true)
    protected String branchDetail;
    @XmlElement(name = "PhoneNo")
    protected long phoneNo;

    /**
     * Gets the value of the branchCode property.
     * 
     */
    public short getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     */
    public void setBranchCode(short value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the micrCode property.
     * 
     */
    public int getMICRCode() {
        return micrCode;
    }

    /**
     * Sets the value of the micrCode property.
     * 
     */
    public void setMICRCode(int value) {
        this.micrCode = value;
    }

    /**
     * Gets the value of the branchDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchDetail() {
        return branchDetail;
    }

    /**
     * Sets the value of the branchDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchDetail(String value) {
        this.branchDetail = value;
    }

    /**
     * Gets the value of the phoneNo property.
     * 
     */
    public long getPhoneNo() {
        return phoneNo;
    }

    /**
     * Sets the value of the phoneNo property.
     * 
     */
    public void setPhoneNo(long value) {
        this.phoneNo = value;
    }

}
