//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PeriodDescription1"/&gt;
 *         &lt;element ref="{}LastYearConsumption1"/&gt;
 *         &lt;element ref="{}ThisYearConsumption1"/&gt;
 *         &lt;element ref="{}PeriodDescription2"/&gt;
 *         &lt;element ref="{}LastYearConsumption2"/&gt;
 *         &lt;element ref="{}ThisYearConsumption2"/&gt;
 *         &lt;element ref="{}PeriodDescription3"/&gt;
 *         &lt;element ref="{}LastYearConsumption3"/&gt;
 *         &lt;element ref="{}ThisYearConsumption3"/&gt;
 *         &lt;element ref="{}PeriodDescription4"/&gt;
 *         &lt;element ref="{}LastYearConsumption4"/&gt;
 *         &lt;element ref="{}ThisYearConsumption4"/&gt;
 *         &lt;element ref="{}PeriodDescription5"/&gt;
 *         &lt;element ref="{}LastYearConsumption5"/&gt;
 *         &lt;element ref="{}ThisYearConsumption5"/&gt;
 *         &lt;element ref="{}PeriodDescription6"/&gt;
 *         &lt;element ref="{}LastYearConsumption6"/&gt;
 *         &lt;element ref="{}ThisYearConsumption6"/&gt;
 *         &lt;element ref="{}PeriodDescription7"/&gt;
 *         &lt;element ref="{}LastYearConsumption7"/&gt;
 *         &lt;element ref="{}ThisYearConsumption7"/&gt;
 *         &lt;element ref="{}PeriodDescription8"/&gt;
 *         &lt;element ref="{}LastYearConsumption8"/&gt;
 *         &lt;element ref="{}ThisYearConsumption8"/&gt;
 *         &lt;element ref="{}PeriodDescription9"/&gt;
 *         &lt;element ref="{}LastYearConsumption9"/&gt;
 *         &lt;element ref="{}ThisYearConsumption9"/&gt;
 *         &lt;element ref="{}PeriodDescription10"/&gt;
 *         &lt;element ref="{}LastYearConsumption10"/&gt;
 *         &lt;element ref="{}ThisYearConsumption10"/&gt;
 *         &lt;element ref="{}PeriodDescription11"/&gt;
 *         &lt;element ref="{}LastYearConsumption11"/&gt;
 *         &lt;element ref="{}ThisYearConsumption11"/&gt;
 *         &lt;element ref="{}PeriodDescription12"/&gt;
 *         &lt;element ref="{}LastYearConsumption12"/&gt;
 *         &lt;element ref="{}ThisYearConsumption12"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periodDescription1",
    "lastYearConsumption1",
    "thisYearConsumption1",
    "periodDescription2",
    "lastYearConsumption2",
    "thisYearConsumption2",
    "periodDescription3",
    "lastYearConsumption3",
    "thisYearConsumption3",
    "periodDescription4",
    "lastYearConsumption4",
    "thisYearConsumption4",
    "periodDescription5",
    "lastYearConsumption5",
    "thisYearConsumption5",
    "periodDescription6",
    "lastYearConsumption6",
    "thisYearConsumption6",
    "periodDescription7",
    "lastYearConsumption7",
    "thisYearConsumption7",
    "periodDescription8",
    "lastYearConsumption8",
    "thisYearConsumption8",
    "periodDescription9",
    "lastYearConsumption9",
    "thisYearConsumption9",
    "periodDescription10",
    "lastYearConsumption10",
    "thisYearConsumption10",
    "periodDescription11",
    "lastYearConsumption11",
    "thisYearConsumption11",
    "periodDescription12",
    "lastYearConsumption12",
    "thisYearConsumption12",
    "serviceAgreeSerialNo"
})
@XmlRootElement(name = "ConsumptionPillars-132")
public class ConsumptionPillars132 {

    @XmlElement(name = "PeriodDescription1", required = true)
    protected String periodDescription1;
    @XmlElement(name = "LastYearConsumption1")
    protected double lastYearConsumption1;
    @XmlElement(name = "ThisYearConsumption1")
    protected double thisYearConsumption1;
    @XmlElement(name = "PeriodDescription2", required = true)
    protected String periodDescription2;
    @XmlElement(name = "LastYearConsumption2")
    protected double lastYearConsumption2;
    @XmlElement(name = "ThisYearConsumption2")
    protected double thisYearConsumption2;
    @XmlElement(name = "PeriodDescription3", required = true)
    protected String periodDescription3;
    @XmlElement(name = "LastYearConsumption3")
    protected double lastYearConsumption3;
    @XmlElement(name = "ThisYearConsumption3")
    protected double thisYearConsumption3;
    @XmlElement(name = "PeriodDescription4", required = true)
    protected String periodDescription4;
    @XmlElement(name = "LastYearConsumption4")
    protected double lastYearConsumption4;
    @XmlElement(name = "ThisYearConsumption4")
    protected double thisYearConsumption4;
    @XmlElement(name = "PeriodDescription5", required = true)
    protected String periodDescription5;
    @XmlElement(name = "LastYearConsumption5")
    protected double lastYearConsumption5;
    @XmlElement(name = "ThisYearConsumption5")
    protected double thisYearConsumption5;
    @XmlElement(name = "PeriodDescription6", required = true)
    protected String periodDescription6;
    @XmlElement(name = "LastYearConsumption6")
    protected double lastYearConsumption6;
    @XmlElement(name = "ThisYearConsumption6")
    protected double thisYearConsumption6;
    @XmlElement(name = "PeriodDescription7", required = true)
    protected String periodDescription7;
    @XmlElement(name = "LastYearConsumption7")
    protected double lastYearConsumption7;
    @XmlElement(name = "ThisYearConsumption7")
    protected double thisYearConsumption7;
    @XmlElement(name = "PeriodDescription8", required = true)
    protected String periodDescription8;
    @XmlElement(name = "LastYearConsumption8")
    protected double lastYearConsumption8;
    @XmlElement(name = "ThisYearConsumption8")
    protected double thisYearConsumption8;
    @XmlElement(name = "PeriodDescription9", required = true)
    protected String periodDescription9;
    @XmlElement(name = "LastYearConsumption9")
    protected double lastYearConsumption9;
    @XmlElement(name = "ThisYearConsumption9")
    protected double thisYearConsumption9;
    @XmlElement(name = "PeriodDescription10", required = true)
    protected String periodDescription10;
    @XmlElement(name = "LastYearConsumption10")
    protected double lastYearConsumption10;
    @XmlElement(name = "ThisYearConsumption10")
    protected double thisYearConsumption10;
    @XmlElement(name = "PeriodDescription11", required = true)
    protected String periodDescription11;
    @XmlElement(name = "LastYearConsumption11")
    protected double lastYearConsumption11;
    @XmlElement(name = "ThisYearConsumption11")
    protected double thisYearConsumption11;
    @XmlElement(name = "PeriodDescription12", required = true)
    protected String periodDescription12;
    @XmlElement(name = "LastYearConsumption12")
    protected double lastYearConsumption12;
    @XmlElement(name = "ThisYearConsumption12")
    protected double thisYearConsumption12;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;

    /**
     * Gets the value of the periodDescription1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription1() {
        return periodDescription1;
    }

    /**
     * Sets the value of the periodDescription1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription1(String value) {
        this.periodDescription1 = value;
    }

    /**
     * Gets the value of the lastYearConsumption1 property.
     * 
     */
    public double getLastYearConsumption1() {
        return lastYearConsumption1;
    }

    /**
     * Sets the value of the lastYearConsumption1 property.
     * 
     */
    public void setLastYearConsumption1(double value) {
        this.lastYearConsumption1 = value;
    }

    /**
     * Gets the value of the thisYearConsumption1 property.
     * 
     */
    public double getThisYearConsumption1() {
        return thisYearConsumption1;
    }

    /**
     * Sets the value of the thisYearConsumption1 property.
     * 
     */
    public void setThisYearConsumption1(double value) {
        this.thisYearConsumption1 = value;
    }

    /**
     * Gets the value of the periodDescription2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription2() {
        return periodDescription2;
    }

    /**
     * Sets the value of the periodDescription2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription2(String value) {
        this.periodDescription2 = value;
    }

    /**
     * Gets the value of the lastYearConsumption2 property.
     * 
     */
    public double getLastYearConsumption2() {
        return lastYearConsumption2;
    }

    /**
     * Sets the value of the lastYearConsumption2 property.
     * 
     */
    public void setLastYearConsumption2(double value) {
        this.lastYearConsumption2 = value;
    }

    /**
     * Gets the value of the thisYearConsumption2 property.
     * 
     */
    public double getThisYearConsumption2() {
        return thisYearConsumption2;
    }

    /**
     * Sets the value of the thisYearConsumption2 property.
     * 
     */
    public void setThisYearConsumption2(double value) {
        this.thisYearConsumption2 = value;
    }

    /**
     * Gets the value of the periodDescription3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription3() {
        return periodDescription3;
    }

    /**
     * Sets the value of the periodDescription3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription3(String value) {
        this.periodDescription3 = value;
    }

    /**
     * Gets the value of the lastYearConsumption3 property.
     * 
     */
    public double getLastYearConsumption3() {
        return lastYearConsumption3;
    }

    /**
     * Sets the value of the lastYearConsumption3 property.
     * 
     */
    public void setLastYearConsumption3(double value) {
        this.lastYearConsumption3 = value;
    }

    /**
     * Gets the value of the thisYearConsumption3 property.
     * 
     */
    public double getThisYearConsumption3() {
        return thisYearConsumption3;
    }

    /**
     * Sets the value of the thisYearConsumption3 property.
     * 
     */
    public void setThisYearConsumption3(double value) {
        this.thisYearConsumption3 = value;
    }

    /**
     * Gets the value of the periodDescription4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription4() {
        return periodDescription4;
    }

    /**
     * Sets the value of the periodDescription4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription4(String value) {
        this.periodDescription4 = value;
    }

    /**
     * Gets the value of the lastYearConsumption4 property.
     * 
     */
    public double getLastYearConsumption4() {
        return lastYearConsumption4;
    }

    /**
     * Sets the value of the lastYearConsumption4 property.
     * 
     */
    public void setLastYearConsumption4(double value) {
        this.lastYearConsumption4 = value;
    }

    /**
     * Gets the value of the thisYearConsumption4 property.
     * 
     */
    public double getThisYearConsumption4() {
        return thisYearConsumption4;
    }

    /**
     * Sets the value of the thisYearConsumption4 property.
     * 
     */
    public void setThisYearConsumption4(double value) {
        this.thisYearConsumption4 = value;
    }

    /**
     * Gets the value of the periodDescription5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription5() {
        return periodDescription5;
    }

    /**
     * Sets the value of the periodDescription5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription5(String value) {
        this.periodDescription5 = value;
    }

    /**
     * Gets the value of the lastYearConsumption5 property.
     * 
     */
    public double getLastYearConsumption5() {
        return lastYearConsumption5;
    }

    /**
     * Sets the value of the lastYearConsumption5 property.
     * 
     */
    public void setLastYearConsumption5(double value) {
        this.lastYearConsumption5 = value;
    }

    /**
     * Gets the value of the thisYearConsumption5 property.
     * 
     */
    public double getThisYearConsumption5() {
        return thisYearConsumption5;
    }

    /**
     * Sets the value of the thisYearConsumption5 property.
     * 
     */
    public void setThisYearConsumption5(double value) {
        this.thisYearConsumption5 = value;
    }

    /**
     * Gets the value of the periodDescription6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription6() {
        return periodDescription6;
    }

    /**
     * Sets the value of the periodDescription6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription6(String value) {
        this.periodDescription6 = value;
    }

    /**
     * Gets the value of the lastYearConsumption6 property.
     * 
     */
    public double getLastYearConsumption6() {
        return lastYearConsumption6;
    }

    /**
     * Sets the value of the lastYearConsumption6 property.
     * 
     */
    public void setLastYearConsumption6(double value) {
        this.lastYearConsumption6 = value;
    }

    /**
     * Gets the value of the thisYearConsumption6 property.
     * 
     */
    public double getThisYearConsumption6() {
        return thisYearConsumption6;
    }

    /**
     * Sets the value of the thisYearConsumption6 property.
     * 
     */
    public void setThisYearConsumption6(double value) {
        this.thisYearConsumption6 = value;
    }

    /**
     * Gets the value of the periodDescription7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription7() {
        return periodDescription7;
    }

    /**
     * Sets the value of the periodDescription7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription7(String value) {
        this.periodDescription7 = value;
    }

    /**
     * Gets the value of the lastYearConsumption7 property.
     * 
     */
    public double getLastYearConsumption7() {
        return lastYearConsumption7;
    }

    /**
     * Sets the value of the lastYearConsumption7 property.
     * 
     */
    public void setLastYearConsumption7(double value) {
        this.lastYearConsumption7 = value;
    }

    /**
     * Gets the value of the thisYearConsumption7 property.
     * 
     */
    public double getThisYearConsumption7() {
        return thisYearConsumption7;
    }

    /**
     * Sets the value of the thisYearConsumption7 property.
     * 
     */
    public void setThisYearConsumption7(double value) {
        this.thisYearConsumption7 = value;
    }

    /**
     * Gets the value of the periodDescription8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription8() {
        return periodDescription8;
    }

    /**
     * Sets the value of the periodDescription8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription8(String value) {
        this.periodDescription8 = value;
    }

    /**
     * Gets the value of the lastYearConsumption8 property.
     * 
     */
    public double getLastYearConsumption8() {
        return lastYearConsumption8;
    }

    /**
     * Sets the value of the lastYearConsumption8 property.
     * 
     */
    public void setLastYearConsumption8(double value) {
        this.lastYearConsumption8 = value;
    }

    /**
     * Gets the value of the thisYearConsumption8 property.
     * 
     */
    public double getThisYearConsumption8() {
        return thisYearConsumption8;
    }

    /**
     * Sets the value of the thisYearConsumption8 property.
     * 
     */
    public void setThisYearConsumption8(double value) {
        this.thisYearConsumption8 = value;
    }

    /**
     * Gets the value of the periodDescription9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription9() {
        return periodDescription9;
    }

    /**
     * Sets the value of the periodDescription9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription9(String value) {
        this.periodDescription9 = value;
    }

    /**
     * Gets the value of the lastYearConsumption9 property.
     * 
     */
    public double getLastYearConsumption9() {
        return lastYearConsumption9;
    }

    /**
     * Sets the value of the lastYearConsumption9 property.
     * 
     */
    public void setLastYearConsumption9(double value) {
        this.lastYearConsumption9 = value;
    }

    /**
     * Gets the value of the thisYearConsumption9 property.
     * 
     */
    public double getThisYearConsumption9() {
        return thisYearConsumption9;
    }

    /**
     * Sets the value of the thisYearConsumption9 property.
     * 
     */
    public void setThisYearConsumption9(double value) {
        this.thisYearConsumption9 = value;
    }

    /**
     * Gets the value of the periodDescription10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription10() {
        return periodDescription10;
    }

    /**
     * Sets the value of the periodDescription10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription10(String value) {
        this.periodDescription10 = value;
    }

    /**
     * Gets the value of the lastYearConsumption10 property.
     * 
     */
    public double getLastYearConsumption10() {
        return lastYearConsumption10;
    }

    /**
     * Sets the value of the lastYearConsumption10 property.
     * 
     */
    public void setLastYearConsumption10(double value) {
        this.lastYearConsumption10 = value;
    }

    /**
     * Gets the value of the thisYearConsumption10 property.
     * 
     */
    public double getThisYearConsumption10() {
        return thisYearConsumption10;
    }

    /**
     * Sets the value of the thisYearConsumption10 property.
     * 
     */
    public void setThisYearConsumption10(double value) {
        this.thisYearConsumption10 = value;
    }

    /**
     * Gets the value of the periodDescription11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription11() {
        return periodDescription11;
    }

    /**
     * Sets the value of the periodDescription11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription11(String value) {
        this.periodDescription11 = value;
    }

    /**
     * Gets the value of the lastYearConsumption11 property.
     * 
     */
    public double getLastYearConsumption11() {
        return lastYearConsumption11;
    }

    /**
     * Sets the value of the lastYearConsumption11 property.
     * 
     */
    public void setLastYearConsumption11(double value) {
        this.lastYearConsumption11 = value;
    }

    /**
     * Gets the value of the thisYearConsumption11 property.
     * 
     */
    public double getThisYearConsumption11() {
        return thisYearConsumption11;
    }

    /**
     * Sets the value of the thisYearConsumption11 property.
     * 
     */
    public void setThisYearConsumption11(double value) {
        this.thisYearConsumption11 = value;
    }

    /**
     * Gets the value of the periodDescription12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodDescription12() {
        return periodDescription12;
    }

    /**
     * Sets the value of the periodDescription12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodDescription12(String value) {
        this.periodDescription12 = value;
    }

    /**
     * Gets the value of the lastYearConsumption12 property.
     * 
     */
    public double getLastYearConsumption12() {
        return lastYearConsumption12;
    }

    /**
     * Sets the value of the lastYearConsumption12 property.
     * 
     */
    public void setLastYearConsumption12(double value) {
        this.lastYearConsumption12 = value;
    }

    /**
     * Gets the value of the thisYearConsumption12 property.
     * 
     */
    public double getThisYearConsumption12() {
        return thisYearConsumption12;
    }

    /**
     * Sets the value of the thisYearConsumption12 property.
     * 
     */
    public void setThisYearConsumption12(double value) {
        this.thisYearConsumption12 = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

}
