//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}AKTOR"/&gt;
 *         &lt;element ref="{}AKTORNAVN"/&gt;
 *         &lt;element ref="{}FAKTURANR"/&gt;
 *         &lt;element ref="{}FREE_TEXT"/&gt;
 *         &lt;element ref="{}MAALEPUNKT"/&gt;
 *         &lt;element ref="{}FAKTURA_TYPE"/&gt;
 *         &lt;element ref="{}KUNDE_TYPE"/&gt;
 *         &lt;element ref="{}FAKTURA_MERKE_SO"/&gt;
 *         &lt;element ref="{}VEDLEGG_FORMAT"/&gt;
 *         &lt;element ref="{}VEDLEGG_EMUXML" minOccurs="0"/&gt;
 *         &lt;element ref="{}VEDLEGG_E2B" minOccurs="0"/&gt;
 *         &lt;element ref="{}VEDLEGG_PDF" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aktor",
    "aktornavn",
    "fakturanr",
    "freeText",
    "maalepunkt",
    "fakturatype",
    "kundetype",
    "grid",
    "fakturamerkeso",
    "vedleggformat",
    "vedleggemuxml",
    //"vedlegge2BObj",
    "vedlegge2B",
    "vedleggpdf",
    "vedlegge2BObj",
    "vedleggehf",
    "vedleggehfObj",
    "nettleieList"
})
@XmlRootElement(name = "FAKTURA")
public class FAKTURA {

    @XmlElement(name = "AKTOR")
    protected int aktor;
    @XmlElement(name = "AKTORNAVN", required = true)
    protected String aktornavn;
    @XmlElement(name = "FAKTURANR", required = true)
    protected String fakturanr;
    @XmlElement(name = "FREE_TEXT", required = true)
    protected String freeText;
    @XmlElement(name = "MAALEPUNKT")
    protected long maalepunkt;
    @XmlElement(name = "FAKTURA_TYPE", required = true)
    protected String fakturatype;
    @XmlElement(name = "KUNDE_TYPE", required = true)
    protected String kundetype;
    @XmlElement(name = "GRID", required = true)
    protected Grid grid;
    @XmlElement(name = "FAKTURA_MERKE_SO", required = true)
    protected String fakturamerkeso;
    @XmlElement(name = "VEDLEGG_FORMAT", required = true)
    protected String vedleggformat;
    @XmlElement(name = "VEDLEGG_EMUXML")
    protected VEDLEGGEMUXML vedleggemuxml;
    @XmlElement(name = "VEDLEGG_E2B")
    protected String vedlegge2B;
    @XmlElement(name = "VEDLEGG_PDF")
    protected String vedleggpdf;
    @XmlElement(name = "VEDLEGG_E2B", required = true)
    protected VEDLEGGE2B vedlegge2BObj;
    @XmlElement(name = "VEDLEGG_EHF", required = true)
    protected VEDLEGGEHF vedleggehfObj;
    @XmlElement(name = "VEDLEGG_EHF", required = true)
    protected String vedleggehf;
    @XmlElement(name = "Nettleie", required = true)
    protected List<Nettleie> nettleieList;

    /**
     * Gets the value of the aktor property.
     * 
     */
    public int getAKTOR() {
        return aktor;
    }

    /**
     * Sets the value of the aktor property.
     * 
     */
    public void setAKTOR(int value) {
        this.aktor = value;
    }

    /**
     * Gets the value of the aktornavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAKTORNAVN() {
        return aktornavn;
    }

    /**
     * Sets the value of the aktornavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAKTORNAVN(String value) {
        this.aktornavn = value;
    }

    /**
     * Gets the value of the fakturanr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAKTURANR() {
        return fakturanr;
    }

    /**
     * Sets the value of the fakturanr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAKTURANR(String value) {
        this.fakturanr = value;
    }

    /**
     * Gets the value of the maalepunkt property.
     * 
     */
    public long getMAALEPUNKT() {
        return maalepunkt;
    }

    /**
     * Sets the value of the maalepunkt property.
     * 
     */
    public void setMAALEPUNKT(long value) {
        this.maalepunkt = value;
    }

    /**
     * Gets the value of the fakturatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAKTURATYPE() {
        return fakturatype;
    }

    /**
     * Sets the value of the fakturatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAKTURATYPE(String value) {
        this.fakturatype = value;
    }

    /**
     * Gets the value of the kundetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKUNDETYPE() {
        return kundetype;
    }

    /**
     * Sets the value of the kundetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKUNDETYPE(String value) {
        this.kundetype = value;
    }

    /**
     * Gets the value of the fakturamerkeso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAKTURAMERKESO() {
        return fakturamerkeso;
    }

    /**
     * Sets the value of the fakturamerkeso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAKTURAMERKESO(String value) {
        this.fakturamerkeso = value;
    }

    /**
     * Gets the value of the vedleggformat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEDLEGGFORMAT() {
        return vedleggformat;
    }

    /**
     * Sets the value of the vedleggformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEDLEGGFORMAT(String value) {
        this.vedleggformat = value;
    }

    /**
     * Gets the value of the vedleggemuxml property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.VEDLEGGEMUXML }
     *     
     */
    public VEDLEGGEMUXML getVEDLEGGEMUXML() {
        return vedleggemuxml;
    }

    /**
     * Sets the value of the vedleggemuxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.VEDLEGGEMUXML }
     *     
     */
    public void setVEDLEGGEMUXML(VEDLEGGEMUXML value) {
        this.vedleggemuxml = value;
    }

    /**
     * Gets the value of the vedlegge2B property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEDLEGGE2B() {
        return vedlegge2B;
    }

    /**
     * Sets the value of the vedlegge2B property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEDLEGGE2B(String value) {
        this.vedlegge2B = value;
    }

    /**
     * Gets the value of the vedleggpdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEDLEGGPDF() {
        return vedleggpdf;
    }

    /**
     * Sets the value of the vedleggpdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEDLEGGPDF(String value) {
        this.vedleggpdf = value;
    }

    /**
     * Gets the value of the vedlegge2B property.
     *
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.VEDLEGGE2B }
     *
     *//*
    public VEDLEGGE2B getVEDLEGGE2B() {
        return vedlegge2BObj;
    }

    *//**
     * Sets the value of the vedlegge2B property.
     *
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.VEDLEGGE2B }
     *
     *//*
    public void setVEDLEGGE2B(VEDLEGGE2B value) {
        this.vedlegge2BObj = value;
    }*/

    public VEDLEGGE2B getVedlegge2BObj() {
        return vedlegge2BObj;
    }

    public void setVedlegge2BObj(VEDLEGGE2B vedlegge2BObj) {
        this.vedlegge2BObj = vedlegge2BObj;
    }

    public String getVedlegge2B() {
        return vedlegge2B;
    }

    public void setVedlegge2B(String vedlegge2B) {
        this.vedlegge2B = vedlegge2B;
    }

    public String getVedleggpdf() {
        return vedleggpdf;
    }

    public void setVedleggpdf(String vedleggpdf) {
        this.vedleggpdf = vedleggpdf;
    }

    public VEDLEGGEHF getVedleggehfObj() {
        return vedleggehfObj;
    }

    public void setVedleggehfObj(VEDLEGGEHF vedleggehfObj) {
        this.vedleggehfObj = vedleggehfObj;
    }

    public String getVedleggehf() {
        return vedleggehf;
    }

    public void setVedleggehf(String vedleggehf) {
        this.vedleggehf = vedleggehf;
    }

    public String getFreeText() {
        return freeText;
    }

    public void setFreeText(String freeText) {
        this.freeText = freeText;
    }

    public Grid getGrid() {
        return grid;
    }

    public void setGrid(Grid grid) {
        this.grid = grid;
    }

    public List<Nettleie> getNettleieList() {
        if(null == nettleieList)
            nettleieList = new ArrayList<>();
        return nettleieList;
    }

    public void setNettleieList(List<Nettleie> nettleieList) {
        this.nettleieList = nettleieList;
    }

}
