//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExportedDate"/>
 *         &lt;element ref="{}NumberOfRecords"/>
 *         &lt;element ref="{}BrandCode"/>
 *         &lt;element ref="{}BrandName"/>
 *         &lt;element ref="{}ExportedMode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exportedDate",
    "numberOfRecords",
    "brandCode",
    "brandName",
    "exportedMode"
})
@XmlRootElement(name = "Header")
public class Header {

    @XmlElement(name = "ExportedDate", required = true)
    protected String exportedDate;
    @XmlElement(name = "NumberOfRecords")
    protected byte numberOfRecords;
    @XmlElement(name = "BrandCode", required = true)
    protected String brandCode;
    @XmlElement(name = "BrandName", required = true)
    protected String brandName;
    @XmlElement(name = "ExportedMode", required = true)
    protected String exportedMode;

    /**
     * Gets the value of the exportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportedDate() {
        return exportedDate;
    }

    /**
     * Sets the value of the exportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportedDate(String value) {
        this.exportedDate = value;
    }

    /**
     * Gets the value of the numberOfRecords property.
     * 
     */
    public byte getNumberOfRecords() {
        return numberOfRecords;
    }

    /**
     * Sets the value of the numberOfRecords property.
     * 
     */
    public void setNumberOfRecords(byte value) {
        this.numberOfRecords = value;
    }

    /**
     * Gets the value of the brandCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * Sets the value of the brandCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandCode(String value) {
        this.brandCode = value;
    }

    /**
     * Gets the value of the brandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * Sets the value of the brandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandName(String value) {
        this.brandName = value;
    }

    /**
     * Gets the value of the exportedMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportedMode() {
        return exportedMode;
    }

    /**
     * Sets the value of the exportedMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportedMode(String value) {
        this.exportedMode = value;
    }

}
