//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}StartDate"/&gt;
 *         &lt;element ref="{}EndDate"/&gt;
 *         &lt;element ref="{}StartMonth"/&gt;
 *         &lt;element ref="{}EndMonth"/&gt;
 *         &lt;element ref="{}Net"/&gt;
 *         &lt;element ref="{}Gross"/&gt;
 *         &lt;element ref="{}StatisticCode"/&gt;
 *         &lt;element ref="{}VatRate"/&gt;
 *         &lt;element ref="{}SuppCode"/&gt;
 *         &lt;element ref="{}Text"/&gt;
 *         &lt;element ref="{}PriceCode"/&gt;
 *         &lt;element ref="{}PriceRate"/&gt;
 *         &lt;element ref="{}Basis"/&gt;
 *         &lt;element ref="{}NoOfDays"/&gt;
 *         &lt;element ref="{}OldC-Reading"/&gt;
 *         &lt;element ref="{}FinalC-Reading"/&gt;
 *         &lt;element ref="{}TotalTaxPrice"/&gt;
 *         &lt;element ref="{}UnitCode"/&gt;
 *         &lt;element ref="{}ProdId"/&gt;
 *         &lt;element ref="{}ProdDenomination"/&gt;
 *         &lt;element ref="{}GrossPrice"/&gt;
 *         &lt;element ref="{}TotalGross"/&gt;
 *         &lt;element ref="{}PriceDenomination"/&gt;
 *         &lt;element ref="{}MiscCode"/&gt;
 *         &lt;element ref="{}B-Account"/&gt;
 *         &lt;element ref="{}Type"/&gt;
 *         &lt;element ref="{}VAT"/&gt;
 *         &lt;element ref="{}DiscPercent"/&gt;
 *         &lt;element ref="{}GrossPriceWithoutTax"/&gt;
 *         &lt;element ref="{}TotalGrossWithoutTax"/&gt;
 *         &lt;element ref="{}TotalTaxPrice_high_precision"/&gt;
 *         &lt;element ref="{}GrossPrice_high_precision"/&gt;
 *         &lt;element ref="{}GrossPriceWithoutTax_high_precision"/&gt;
 *         &lt;element ref="{}ActivityType"/&gt;
 *         &lt;element ref="{}ActivitySubType"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *         &lt;element ref="{}ProductCodePass-ThroughInvoice"/&gt;
 *         &lt;element ref="{}PriceDenominationGross"/&gt;
 *         &lt;element ref="{}PriceDenominationGrossWithoutTax"/&gt;
 *         &lt;element ref="{}PriceDenominationTax"/&gt;
 *         &lt;element ref="{}MiscCodeNew"/&gt;
 *         &lt;element ref="{}TextNew"/&gt;
 *         &lt;element ref="{}DiscAmount"/&gt;
 *         &lt;element ref="{}SuppSubscriptionPrice"/&gt;
 *         &lt;element ref="{}FireValue"/&gt;
 *         &lt;element ref="{}ProductSaleId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startDate",
    "endDate",
    "startMonth",
    "endMonth",
    "net",
    "gross",
    "statisticCode",
    "vatRate",
    "suppCode",
    "text",
    "priceCode",
    "priceRate",
    "basis",
    "noOfDays",
    "oldCReading",
    "finalCReading",
    "totalTaxPrice",
    "unitCode",
    "prodId",
    "prodDenomination",
    "grossPrice",
    "totalGross",
    "priceDenomination",
    "miscCode",
    "bAccount",
    "type",
    "vat",
    "discPercent",
    "grossPriceWithoutTax",
    "totalGrossWithoutTax",
    "totalTaxPriceHighPrecision",
    "grossPriceHighPrecision",
    "grossPriceWithoutTaxHighPrecision",
    "activityType",
    "activitySubType",
    "serviceAgreeSerialNo",
    "productCodePassThroughInvoice",
    "priceDenominationGross",
    "priceDenominationGrossWithoutTax",
    "priceDenominationTax",
    "miscCodeNew",
    "textNew",
    "discAmount",
    "suppSubscriptionPrice",
    "fireValue",
    "productSaleId"
})
@XmlRootElement(name = "InvoiceLine-120")
public class InvoiceLine120 {

    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "StartMonth", required = true)
    protected String startMonth;
    @XmlElement(name = "EndMonth", required = true)
    protected String endMonth;
    @XmlElement(name = "Net")
    protected double net;
    @XmlElement(name = "Gross")
    protected double gross;
    @XmlElement(name = "StatisticCode", required = true)
    protected String statisticCode;
    @XmlElement(name = "VatRate")
    protected double vatRate;
    @XmlElement(name = "SuppCode", required = true)
    protected String suppCode;
    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "PriceCode", required = true)
    protected String priceCode;
    @XmlElement(name = "PriceRate")
    protected double priceRate;
    @XmlElement(name = "Basis")
    protected double basis;
    @XmlElement(name = "NoOfDays")
    protected byte noOfDays;
    @XmlElement(name = "OldC-Reading")
    protected double oldCReading;
    @XmlElement(name = "FinalC-Reading")
    protected double finalCReading;
    @XmlElement(name = "TotalTaxPrice")
    protected double totalTaxPrice;
    @XmlElement(name = "UnitCode", required = true)
    protected String unitCode;
    @XmlElement(name = "ProdId", required = true)
    protected String prodId;
    @XmlElement(name = "ProdDenomination", required = true)
    protected String prodDenomination;
    @XmlElement(name = "GrossPrice")
    protected double grossPrice;
    @XmlElement(name = "TotalGross")
    protected double totalGross;
    @XmlElement(name = "PriceDenomination", required = true)
    protected String priceDenomination;
    @XmlElement(name = "MiscCode")
    protected byte miscCode;
    @XmlElement(name = "B-Account", required = true)
    protected String bAccount;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "VAT")
    protected double vat;
    @XmlElement(name = "DiscPercent")
    protected double discPercent;
    @XmlElement(name = "GrossPriceWithoutTax")
    protected double grossPriceWithoutTax;
    @XmlElement(name = "TotalGrossWithoutTax")
    protected double totalGrossWithoutTax;
    @XmlElement(name = "TotalTaxPrice_high_precision")
    protected double totalTaxPriceHighPrecision;
    @XmlElement(name = "GrossPrice_high_precision")
    protected double grossPriceHighPrecision;
    @XmlElement(name = "GrossPriceWithoutTax_high_precision")
    protected double grossPriceWithoutTaxHighPrecision;
    @XmlElement(name = "ActivityType", required = true)
    protected String activityType;
    @XmlElement(name = "ActivitySubType", required = true)
    protected String activitySubType;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;
    @XmlElement(name = "ProductCodePass-ThroughInvoice")
    protected byte productCodePassThroughInvoice;
    @XmlElement(name = "PriceDenominationGross", required = true)
    protected String priceDenominationGross;
    @XmlElement(name = "PriceDenominationGrossWithoutTax", required = true)
    protected String priceDenominationGrossWithoutTax;
    @XmlElement(name = "PriceDenominationTax", required = true)
    protected String priceDenominationTax;
    @XmlElement(name = "MiscCodeNew")
    protected byte miscCodeNew;
    @XmlElement(name = "TextNew", required = true)
    protected String textNew;
    @XmlElement(name = "DiscAmount")
    protected double discAmount;
    @XmlElement(name = "SuppSubscriptionPrice")
    protected double suppSubscriptionPrice;
    @XmlElement(name = "FireValue")
    protected double fireValue;
    @XmlElement(name = "ProductSaleId")
    protected byte productSaleId;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the startMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartMonth() {
        return startMonth;
    }

    /**
     * Sets the value of the startMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartMonth(String value) {
        this.startMonth = value;
    }

    /**
     * Gets the value of the endMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndMonth() {
        return endMonth;
    }

    /**
     * Sets the value of the endMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndMonth(String value) {
        this.endMonth = value;
    }

    /**
     * Gets the value of the net property.
     * 
     */
    public double getNet() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     */
    public void setNet(double value) {
        this.net = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     */
    public double getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     */
    public void setGross(double value) {
        this.gross = value;
    }

    /**
     * Gets the value of the statisticCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticCode() {
        return statisticCode;
    }

    /**
     * Sets the value of the statisticCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticCode(String value) {
        this.statisticCode = value;
    }

    /**
     * Gets the value of the vatRate property.
     * 
     */
    public double getVatRate() {
        return vatRate;
    }

    /**
     * Sets the value of the vatRate property.
     * 
     */
    public void setVatRate(double value) {
        this.vatRate = value;
    }

    /**
     * Gets the value of the suppCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppCode() {
        return suppCode;
    }

    /**
     * Sets the value of the suppCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppCode(String value) {
        this.suppCode = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the priceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceCode() {
        return priceCode;
    }

    /**
     * Sets the value of the priceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceCode(String value) {
        this.priceCode = value;
    }

    /**
     * Gets the value of the priceRate property.
     * 
     */
    public double getPriceRate() {
        return priceRate;
    }

    /**
     * Sets the value of the priceRate property.
     * 
     */
    public void setPriceRate(double value) {
        this.priceRate = value;
    }

    /**
     * Gets the value of the basis property.
     * 
     */
    public double getBasis() {
        return basis;
    }

    /**
     * Sets the value of the basis property.
     * 
     */
    public void setBasis(double value) {
        this.basis = value;
    }

    /**
     * Gets the value of the noOfDays property.
     * 
     */
    public byte getNoOfDays() {
        return noOfDays;
    }

    /**
     * Sets the value of the noOfDays property.
     * 
     */
    public void setNoOfDays(byte value) {
        this.noOfDays = value;
    }

    /**
     * Gets the value of the oldCReading property.
     * 
     */
    public double getOldCReading() {
        return oldCReading;
    }

    /**
     * Sets the value of the oldCReading property.
     * 
     */
    public void setOldCReading(double value) {
        this.oldCReading = value;
    }

    /**
     * Gets the value of the finalCReading property.
     * 
     */
    public double getFinalCReading() {
        return finalCReading;
    }

    /**
     * Sets the value of the finalCReading property.
     * 
     */
    public void setFinalCReading(double value) {
        this.finalCReading = value;
    }

    /**
     * Gets the value of the totalTaxPrice property.
     * 
     */
    public double getTotalTaxPrice() {
        return totalTaxPrice;
    }

    /**
     * Sets the value of the totalTaxPrice property.
     * 
     */
    public void setTotalTaxPrice(double value) {
        this.totalTaxPrice = value;
    }

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the prodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * Sets the value of the prodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdId(String value) {
        this.prodId = value;
    }

    /**
     * Gets the value of the prodDenomination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDenomination() {
        return prodDenomination;
    }

    /**
     * Sets the value of the prodDenomination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDenomination(String value) {
        this.prodDenomination = value;
    }

    /**
     * Gets the value of the grossPrice property.
     * 
     */
    public double getGrossPrice() {
        return grossPrice;
    }

    /**
     * Sets the value of the grossPrice property.
     * 
     */
    public void setGrossPrice(double value) {
        this.grossPrice = value;
    }

    /**
     * Gets the value of the totalGross property.
     * 
     */
    public double getTotalGross() {
        return totalGross;
    }

    /**
     * Sets the value of the totalGross property.
     * 
     */
    public void setTotalGross(double value) {
        this.totalGross = value;
    }

    /**
     * Gets the value of the priceDenomination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceDenomination() {
        return priceDenomination;
    }

    /**
     * Sets the value of the priceDenomination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceDenomination(String value) {
        this.priceDenomination = value;
    }

    /**
     * Gets the value of the miscCode property.
     * 
     */
    public byte getMiscCode() {
        return miscCode;
    }

    /**
     * Sets the value of the miscCode property.
     * 
     */
    public void setMiscCode(byte value) {
        this.miscCode = value;
    }

    /**
     * Gets the value of the bAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAccount() {
        return bAccount;
    }

    /**
     * Sets the value of the bAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAccount(String value) {
        this.bAccount = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     */
    public double getVAT() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     */
    public void setVAT(double value) {
        this.vat = value;
    }

    /**
     * Gets the value of the discPercent property.
     * 
     */
    public double getDiscPercent() {
        return discPercent;
    }

    /**
     * Sets the value of the discPercent property.
     * 
     */
    public void setDiscPercent(double value) {
        this.discPercent = value;
    }

    /**
     * Gets the value of the grossPriceWithoutTax property.
     * 
     */
    public double getGrossPriceWithoutTax() {
        return grossPriceWithoutTax;
    }

    /**
     * Sets the value of the grossPriceWithoutTax property.
     * 
     */
    public void setGrossPriceWithoutTax(double value) {
        this.grossPriceWithoutTax = value;
    }

    /**
     * Gets the value of the totalGrossWithoutTax property.
     * 
     */
    public double getTotalGrossWithoutTax() {
        return totalGrossWithoutTax;
    }

    /**
     * Sets the value of the totalGrossWithoutTax property.
     * 
     */
    public void setTotalGrossWithoutTax(double value) {
        this.totalGrossWithoutTax = value;
    }

    /**
     * Gets the value of the totalTaxPriceHighPrecision property.
     * 
     */
    public double getTotalTaxPriceHighPrecision() {
        return totalTaxPriceHighPrecision;
    }

    /**
     * Sets the value of the totalTaxPriceHighPrecision property.
     * 
     */
    public void setTotalTaxPriceHighPrecision(double value) {
        this.totalTaxPriceHighPrecision = value;
    }

    /**
     * Gets the value of the grossPriceHighPrecision property.
     * 
     */
    public double getGrossPriceHighPrecision() {
        return grossPriceHighPrecision;
    }

    /**
     * Sets the value of the grossPriceHighPrecision property.
     * 
     */
    public void setGrossPriceHighPrecision(double value) {
        this.grossPriceHighPrecision = value;
    }

    /**
     * Gets the value of the grossPriceWithoutTaxHighPrecision property.
     * 
     */
    public double getGrossPriceWithoutTaxHighPrecision() {
        return grossPriceWithoutTaxHighPrecision;
    }

    /**
     * Sets the value of the grossPriceWithoutTaxHighPrecision property.
     * 
     */
    public void setGrossPriceWithoutTaxHighPrecision(double value) {
        this.grossPriceWithoutTaxHighPrecision = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the activitySubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivitySubType() {
        return activitySubType;
    }

    /**
     * Sets the value of the activitySubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivitySubType(String value) {
        this.activitySubType = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

    /**
     * Gets the value of the productCodePassThroughInvoice property.
     * 
     */
    public byte getProductCodePassThroughInvoice() {
        return productCodePassThroughInvoice;
    }

    /**
     * Sets the value of the productCodePassThroughInvoice property.
     * 
     */
    public void setProductCodePassThroughInvoice(byte value) {
        this.productCodePassThroughInvoice = value;
    }

    /**
     * Gets the value of the priceDenominationGross property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceDenominationGross() {
        return priceDenominationGross;
    }

    /**
     * Sets the value of the priceDenominationGross property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceDenominationGross(String value) {
        this.priceDenominationGross = value;
    }

    /**
     * Gets the value of the priceDenominationGrossWithoutTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceDenominationGrossWithoutTax() {
        return priceDenominationGrossWithoutTax;
    }

    /**
     * Sets the value of the priceDenominationGrossWithoutTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceDenominationGrossWithoutTax(String value) {
        this.priceDenominationGrossWithoutTax = value;
    }

    /**
     * Gets the value of the priceDenominationTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceDenominationTax() {
        return priceDenominationTax;
    }

    /**
     * Sets the value of the priceDenominationTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceDenominationTax(String value) {
        this.priceDenominationTax = value;
    }

    /**
     * Gets the value of the miscCodeNew property.
     * 
     */
    public byte getMiscCodeNew() {
        return miscCodeNew;
    }

    /**
     * Sets the value of the miscCodeNew property.
     * 
     */
    public void setMiscCodeNew(byte value) {
        this.miscCodeNew = value;
    }

    /**
     * Gets the value of the textNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextNew() {
        return textNew;
    }

    /**
     * Sets the value of the textNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextNew(String value) {
        this.textNew = value;
    }

    /**
     * Gets the value of the discAmount property.
     * 
     */
    public double getDiscAmount() {
        return discAmount;
    }

    /**
     * Sets the value of the discAmount property.
     * 
     */
    public void setDiscAmount(double value) {
        this.discAmount = value;
    }

    /**
     * Gets the value of the suppSubscriptionPrice property.
     * 
     */
    public double getSuppSubscriptionPrice() {
        return suppSubscriptionPrice;
    }

    /**
     * Sets the value of the suppSubscriptionPrice property.
     * 
     */
    public void setSuppSubscriptionPrice(double value) {
        this.suppSubscriptionPrice = value;
    }

    /**
     * Gets the value of the fireValue property.
     * 
     */
    public double getFireValue() {
        return fireValue;
    }

    /**
     * Sets the value of the fireValue property.
     * 
     */
    public void setFireValue(double value) {
        this.fireValue = value;
    }

    /**
     * Gets the value of the productSaleId property.
     * 
     */
    public byte getProductSaleId() {
        return productSaleId;
    }

    /**
     * Sets the value of the productSaleId property.
     * 
     */
    public void setProductSaleId(byte value) {
        this.productSaleId = value;
    }

}
