//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 05:23:10 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}GrossAmount"/&gt;
 *         &lt;element ref="{}VatTotalsAmount"/&gt;
 *         &lt;element ref="{}NetAmount"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grossAmount",
    "vatTotalsAmount",
    "netAmount" ,
    "origGrossAmount",
    "lineItemTotalsAmount"
})
@XmlRootElement(name = "InvoiceTotals")
public class InvoiceTotals {

    @XmlElement(name = "GrossAmount")
    protected double grossAmount;
    @XmlElement(name = "VatTotalsAmount")
    protected double vatTotalsAmount;
    @XmlElement(name = "NetAmount")
    protected double netAmount;
    @XmlElement(name = "OrigGrossAmount")
    protected double origGrossAmount;
    @XmlElement(name = "LineItemTotalsAmount")
    protected double lineItemTotalsAmount;


    /**
     * Gets the value of the grossAmount property.
     * 
     */
    public double getGrossAmount() {
        return grossAmount;
    }

    /**
     * Sets the value of the grossAmount property.
     * 
     */
    public void setGrossAmount(double value) {
        this.grossAmount = value;
    }

    /**
     * Gets the value of the vatTotalsAmount property.
     * 
     */
    public double getVatTotalsAmount() {
        return vatTotalsAmount;
    }

    /**
     * Sets the value of the vatTotalsAmount property.
     * 
     */
    public void setVatTotalsAmount(double value) {
        this.vatTotalsAmount = value;
    }

    /**
     * Gets the value of the netAmount property.
     * 
     */
    public double getNetAmount() {
        return netAmount;
    }

    /**
     * Sets the value of the netAmount property.
     * 
     */
    public void setNetAmount(double value) {
        this.netAmount = value;
    }

    public double getOrigGrossAmount() {
        return origGrossAmount;
    }

    public void setOrigGrossAmount(double origGrossAmount) {
        this.origGrossAmount = origGrossAmount;
    }

    public double getLineItemTotalsAmount() {
        return lineItemTotalsAmount;
    }

    public void setLineItemTotalsAmount(double lineItemTotalsAmount) {
        this.lineItemTotalsAmount = lineItemTotalsAmount;
    }
}
