//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 05:23:10 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}InvoiceType"/&gt;
 *         &lt;element ref="{}InvoiceStatus"/&gt;
 *         &lt;element ref="{}InvoiceNumber"/&gt;
 *         &lt;element ref="{}InvoiceDate"/&gt;
 *         &lt;element ref="{}Supplier"/&gt;
 *         &lt;element ref="{}Buyer"/&gt;
 *         &lt;element ref="{}Payment"/&gt;
 *         &lt;element ref="{}EnergyHeader"/&gt;
 *         &lt;element ref="{}Attachment"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceType",
    "invoiceStatus",
    "invoiceNumber",
    "invoiceDate",
    "supplier",
    "buyer",
    "payment",
    "energyHeader",
    "attachment"
})
@XmlRootElement(name = "InvoiceHeader")
public class InvoiceHeader {

    @XmlElement(name = "InvoiceType", required = true)
    protected InvoiceType invoiceType;
    @XmlElement(name = "InvoiceStatus")
    protected byte invoiceStatus;
    @XmlElement(name = "InvoiceNumber")
    protected int invoiceNumber;
    @XmlElement(name = "InvoiceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "Supplier", required = true)
    protected Supplier supplier;
    @XmlElement(name = "Buyer", required = true)
    protected Buyer buyer;
    @XmlElement(name = "Payment", required = true)
    protected Payment payment;
    @XmlElement(name = "EnergyHeader", required = true)
    protected EnergyHeader energyHeader;
    @XmlElement(name = "Attachment", required = true)
    protected Attachment attachment;

    /**
     * Gets the value of the invoiceType property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceType }
     *     
     */
    public InvoiceType getInvoiceType() {
        return invoiceType;
    }

    /**
     * Sets the value of the invoiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceType }
     *     
     */
    public void setInvoiceType(InvoiceType value) {
        this.invoiceType = value;
    }

    /**
     * Gets the value of the invoiceStatus property.
     * 
     */
    public byte getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * Sets the value of the invoiceStatus property.
     * 
     */
    public void setInvoiceStatus(byte value) {
        this.invoiceStatus = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     */
    public int getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     */
    public void setInvoiceNumber(int value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.Supplier }
     *     
     */
    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.Supplier }
     *     
     */
    public void setSupplier(Supplier value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the buyer property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.Buyer }
     *     
     */
    public Buyer getBuyer() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.Buyer }
     *     
     */
    public void setBuyer(Buyer value) {
        this.buyer = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the energyHeader property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.EnergyHeader }
     *     
     */
    public EnergyHeader getEnergyHeader() {
        return energyHeader;
    }

    /**
     * Sets the value of the energyHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.EnergyHeader }
     *     
     */
    public void setEnergyHeader(EnergyHeader value) {
        this.energyHeader = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.Attachment }
     *     
     */
    public Attachment getAttachment() {
        return attachment;
    }

    /**
     * Sets the value of the attachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.Attachment }
     *     
     */
    public void setAttachment(Attachment value) {
        this.attachment = value;
    }

}
