//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}GrossSettled"/&gt;
 *         &lt;element ref="{}NetSettled"/&gt;
 *         &lt;element ref="{}VatSettled"/&gt;
 *         &lt;element ref="{}GrossB-Account"/&gt;
 *         &lt;element ref="{}NetB-Account"/&gt;
 *         &lt;element ref="{}VatB-Account"/&gt;
 *         &lt;element ref="{}BAccountTermNo"/&gt;
 *         &lt;element ref="{}BAccountTermStartDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}BAccountTermEndDate" minOccurs="0"/&gt;
 *         &lt;element ref="{}GrossWriteBacks"/&gt;
 *         &lt;element ref="{}NetWriteBacks"/&gt;
 *         &lt;element ref="{}VatWriteBacks"/&gt;
 *         &lt;element ref="{}GrossMisc"/&gt;
 *         &lt;element ref="{}NetMisc"/&gt;
 *         &lt;element ref="{}VatMisc"/&gt;
 *         &lt;element ref="{}GrossItem"/&gt;
 *         &lt;element ref="{}NetItem"/&gt;
 *         &lt;element ref="{}VatItem"/&gt;
 *         &lt;element ref="{}VatTotal"/&gt;
 *         &lt;element ref="{}GrossTax"/&gt;
 *         &lt;element ref="{}NetTotal"/&gt;
 *         &lt;element ref="{}GrossTotal"/&gt;
 *         &lt;element ref="{}GrossSettledAndWriteBacks"/&gt;
 *         &lt;element ref="{}NetSettledAndWriteBacks"/&gt;
 *         &lt;element ref="{}VatSettledAndWriteBacks"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *         &lt;element ref="{}NetWithTax"/&gt;
 *         &lt;element ref="{}GrossWithTax"/&gt;
 *         &lt;element ref="{}NetNoTax"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grossSettled",
    "netSettled",
    "vatSettled",
    "grossBAccount",
    "netBAccount",
    "vatBAccount",
    "bAccountTermNo",
    "bAccountTermStartDate",
    "bAccountTermEndDate",
    "grossWriteBacks",
    "netWriteBacks",
    "vatWriteBacks",
    "grossMisc",
    "netMisc",
    "vatMisc",
    "grossItem",
    "netItem",
    "vatItem",
    "vatTotal",
    "grossTax",
    "netTotal",
    "grossTotal",
    "grossSettledAndWriteBacks",
    "netSettledAndWriteBacks",
    "vatSettledAndWriteBacks",
    "serviceAgreeSerialNo",
    "netWithTax",
    "grossWithTax",
    "netNoTax"
})
@XmlRootElement(name = "InvoiceOrderAmounts-113")
public class InvoiceOrderAmounts113 {

    @XmlElement(name = "GrossSettled")
    protected double grossSettled;
    @XmlElement(name = "NetSettled")
    protected double netSettled;
    @XmlElement(name = "VatSettled")
    protected double vatSettled;
    @XmlElement(name = "GrossB-Account")
    protected double grossBAccount;
    @XmlElement(name = "NetB-Account")
    protected double netBAccount;
    @XmlElement(name = "VatB-Account")
    protected double vatBAccount;
    @XmlElement(name = "BAccountTermNo")
    protected byte bAccountTermNo;
    @XmlElement(name = "BAccountTermStartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar bAccountTermStartDate;
    @XmlElement(name = "BAccountTermEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar bAccountTermEndDate;
    @XmlElement(name = "GrossWriteBacks")
    protected double grossWriteBacks;
    @XmlElement(name = "NetWriteBacks")
    protected double netWriteBacks;
    @XmlElement(name = "VatWriteBacks")
    protected double vatWriteBacks;
    @XmlElement(name = "GrossMisc")
    protected double grossMisc;
    @XmlElement(name = "NetMisc")
    protected double netMisc;
    @XmlElement(name = "VatMisc")
    protected double vatMisc;
    @XmlElement(name = "GrossItem")
    protected double grossItem;
    @XmlElement(name = "NetItem")
    protected double netItem;
    @XmlElement(name = "VatItem")
    protected double vatItem;
    @XmlElement(name = "VatTotal")
    protected double vatTotal;
    @XmlElement(name = "GrossTax")
    protected double grossTax;
    @XmlElement(name = "NetTotal")
    protected double netTotal;
    @XmlElement(name = "GrossTotal")
    protected double grossTotal;
    @XmlElement(name = "GrossSettledAndWriteBacks")
    protected double grossSettledAndWriteBacks;
    @XmlElement(name = "NetSettledAndWriteBacks")
    protected double netSettledAndWriteBacks;
    @XmlElement(name = "VatSettledAndWriteBacks")
    protected double vatSettledAndWriteBacks;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;
    @XmlElement(name = "NetWithTax")
    protected double netWithTax;
    @XmlElement(name = "GrossWithTax")
    protected double grossWithTax;
    @XmlElement(name = "NetNoTax")
    protected double netNoTax;

    /**
     * Gets the value of the grossSettled property.
     * 
     */
    public double getGrossSettled() {
        return grossSettled;
    }

    /**
     * Sets the value of the grossSettled property.
     * 
     */
    public void setGrossSettled(double value) {
        this.grossSettled = value;
    }

    /**
     * Gets the value of the netSettled property.
     * 
     */
    public double getNetSettled() {
        return netSettled;
    }

    /**
     * Sets the value of the netSettled property.
     * 
     */
    public void setNetSettled(double value) {
        this.netSettled = value;
    }

    /**
     * Gets the value of the vatSettled property.
     * 
     */
    public double getVatSettled() {
        return vatSettled;
    }

    /**
     * Sets the value of the vatSettled property.
     * 
     */
    public void setVatSettled(double value) {
        this.vatSettled = value;
    }

    /**
     * Gets the value of the grossBAccount property.
     * 
     */
    public double getGrossBAccount() {
        return grossBAccount;
    }

    /**
     * Sets the value of the grossBAccount property.
     * 
     */
    public void setGrossBAccount(double value) {
        this.grossBAccount = value;
    }

    /**
     * Gets the value of the netBAccount property.
     * 
     */
    public double getNetBAccount() {
        return netBAccount;
    }

    /**
     * Sets the value of the netBAccount property.
     * 
     */
    public void setNetBAccount(double value) {
        this.netBAccount = value;
    }

    /**
     * Gets the value of the vatBAccount property.
     * 
     */
    public double getVatBAccount() {
        return vatBAccount;
    }

    /**
     * Sets the value of the vatBAccount property.
     * 
     */
    public void setVatBAccount(double value) {
        this.vatBAccount = value;
    }

    /**
     * Gets the value of the bAccountTermNo property.
     * 
     */
    public byte getBAccountTermNo() {
        return bAccountTermNo;
    }

    /**
     * Sets the value of the bAccountTermNo property.
     * 
     */
    public void setBAccountTermNo(byte value) {
        this.bAccountTermNo = value;
    }

    /**
     * Gets the value of the bAccountTermStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBAccountTermStartDate() {
        return bAccountTermStartDate;
    }

    /**
     * Sets the value of the bAccountTermStartDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setBAccountTermStartDate(XMLGregorianCalendar value) {
        this.bAccountTermStartDate = value;
    }

    /**
     * Gets the value of the bAccountTermEndDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBAccountTermEndDate() {
        return bAccountTermEndDate;
    }

    /**
     * Sets the value of the bAccountTermEndDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBAccountTermEndDate(XMLGregorianCalendar value) {
        this.bAccountTermEndDate = value;
    }

    /**
     * Gets the value of the grossWriteBacks property.
     * 
     */
    public double getGrossWriteBacks() {
        return grossWriteBacks;
    }

    /**
     * Sets the value of the grossWriteBacks property.
     * 
     */
    public void setGrossWriteBacks(double value) {
        this.grossWriteBacks = value;
    }

    /**
     * Gets the value of the netWriteBacks property.
     * 
     */
    public double getNetWriteBacks() {
        return netWriteBacks;
    }

    /**
     * Sets the value of the netWriteBacks property.
     * 
     */
    public void setNetWriteBacks(double value) {
        this.netWriteBacks = value;
    }

    /**
     * Gets the value of the vatWriteBacks property.
     * 
     */
    public double getVatWriteBacks() {
        return vatWriteBacks;
    }

    /**
     * Sets the value of the vatWriteBacks property.
     * 
     */
    public void setVatWriteBacks(double value) {
        this.vatWriteBacks = value;
    }

    /**
     * Gets the value of the grossMisc property.
     * 
     */
    public double getGrossMisc() {
        return grossMisc;
    }

    /**
     * Sets the value of the grossMisc property.
     * 
     */
    public void setGrossMisc(double value) {
        this.grossMisc = value;
    }

    /**
     * Gets the value of the netMisc property.
     * 
     */
    public double getNetMisc() {
        return netMisc;
    }

    /**
     * Sets the value of the netMisc property.
     * 
     */
    public void setNetMisc(double value) {
        this.netMisc = value;
    }

    /**
     * Gets the value of the vatMisc property.
     * 
     */
    public double getVatMisc() {
        return vatMisc;
    }

    /**
     * Sets the value of the vatMisc property.
     * 
     */
    public void setVatMisc(double value) {
        this.vatMisc = value;
    }

    /**
     * Gets the value of the grossItem property.
     * 
     */
    public double getGrossItem() {
        return grossItem;
    }

    /**
     * Sets the value of the grossItem property.
     * 
     */
    public void setGrossItem(double value) {
        this.grossItem = value;
    }

    /**
     * Gets the value of the netItem property.
     * 
     */
    public double getNetItem() {
        return netItem;
    }

    /**
     * Sets the value of the netItem property.
     * 
     */
    public void setNetItem(double value) {
        this.netItem = value;
    }

    /**
     * Gets the value of the vatItem property.
     * 
     */
    public double getVatItem() {
        return vatItem;
    }

    /**
     * Sets the value of the vatItem property.
     * 
     */
    public void setVatItem(double value) {
        this.vatItem = value;
    }

    /**
     * Gets the value of the vatTotal property.
     * 
     */
    public double getVatTotal() {
        return vatTotal;
    }

    /**
     * Sets the value of the vatTotal property.
     * 
     */
    public void setVatTotal(double value) {
        this.vatTotal = value;
    }

    /**
     * Gets the value of the grossTax property.
     * 
     */
    public double getGrossTax() {
        return grossTax;
    }

    /**
     * Sets the value of the grossTax property.
     * 
     */
    public void setGrossTax(double value) {
        this.grossTax = value;
    }

    /**
     * Gets the value of the netTotal property.
     * 
     */
    public double getNetTotal() {
        return netTotal;
    }

    /**
     * Sets the value of the netTotal property.
     * 
     */
    public void setNetTotal(double value) {
        this.netTotal = value;
    }

    /**
     * Gets the value of the grossTotal property.
     * 
     */
    public double getGrossTotal() {
        return grossTotal;
    }

    /**
     * Sets the value of the grossTotal property.
     * 
     */
    public void setGrossTotal(double value) {
        this.grossTotal = value;
    }

    /**
     * Gets the value of the grossSettledAndWriteBacks property.
     * 
     */
    public double getGrossSettledAndWriteBacks() {
        return grossSettledAndWriteBacks;
    }

    /**
     * Sets the value of the grossSettledAndWriteBacks property.
     * 
     */
    public void setGrossSettledAndWriteBacks(double value) {
        this.grossSettledAndWriteBacks = value;
    }

    /**
     * Gets the value of the netSettledAndWriteBacks property.
     * 
     */
    public double getNetSettledAndWriteBacks() {
        return netSettledAndWriteBacks;
    }

    /**
     * Sets the value of the netSettledAndWriteBacks property.
     * 
     */
    public void setNetSettledAndWriteBacks(double value) {
        this.netSettledAndWriteBacks = value;
    }

    /**
     * Gets the value of the vatSettledAndWriteBacks property.
     * 
     */
    public double getVatSettledAndWriteBacks() {
        return vatSettledAndWriteBacks;
    }

    /**
     * Sets the value of the vatSettledAndWriteBacks property.
     * 
     */
    public void setVatSettledAndWriteBacks(double value) {
        this.vatSettledAndWriteBacks = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

    /**
     * Gets the value of the netWithTax property.
     * 
     */
    public double getNetWithTax() {
        return netWithTax;
    }

    /**
     * Sets the value of the netWithTax property.
     * 
     */
    public void setNetWithTax(double value) {
        this.netWithTax = value;
    }

    /**
     * Gets the value of the grossWithTax property.
     * 
     */
    public double getGrossWithTax() {
        return grossWithTax;
    }

    /**
     * Sets the value of the grossWithTax property.
     * 
     */
    public void setGrossWithTax(double value) {
        this.grossWithTax = value;
    }

    /**
     * Gets the value of the netNoTax property.
     * 
     */
    public double getNetNoTax() {
        return netNoTax;
    }

    /**
     * Sets the value of the netNoTax property.
     * 
     */
    public void setNetNoTax(double value) {
        this.netNoTax = value;
    }

}
