//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 05:23:10 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}GrossAmount"/&gt;
 *         &lt;element ref="{}VatTotalsAmount"/&gt;
 *         &lt;element ref="{}NetAmount"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grossAmount",
    "vatTotalsAmount",
    "netAmount"
})
@XmlRootElement(name = "InvoiceTotals")
public class InvoiceTotals {

    @XmlElement(name = "GrossAmount")
    protected float grossAmount;
    @XmlElement(name = "VatTotalsAmount")
    protected float vatTotalsAmount;
    @XmlElement(name = "NetAmount")
    protected float netAmount;

    /**
     * Gets the value of the grossAmount property.
     * 
     */
    public float getGrossAmount() {
        return grossAmount;
    }

    /**
     * Sets the value of the grossAmount property.
     * 
     */
    public void setGrossAmount(float value) {
        this.grossAmount = value;
    }

    /**
     * Gets the value of the vatTotalsAmount property.
     * 
     */
    public float getVatTotalsAmount() {
        return vatTotalsAmount;
    }

    /**
     * Sets the value of the vatTotalsAmount property.
     * 
     */
    public void setVatTotalsAmount(float value) {
        this.vatTotalsAmount = value;
    }

    /**
     * Gets the value of the netAmount property.
     * 
     */
    public float getNetAmount() {
        return netAmount;
    }

    /**
     * Sets the value of the netAmount property.
     * 
     */
    public void setNetAmount(float value) {
        this.netAmount = value;
    }

}
