//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.miles.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BankName_QNAME = new QName("", "BankName");
    private final static QName _MICRCode_QNAME = new QName("", "MICRCode");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _OpeningBalance_QNAME = new QName("", "OpeningBalance");
    private final static QName _NumberOfRecords_QNAME = new QName("", "NumberOfRecords");
    private final static QName _AccountOpenDate_QNAME = new QName("", "AccountOpenDate");
    private final static QName _BrandCode_QNAME = new QName("", "BrandCode");
    private final static QName _CreditAmount_QNAME = new QName("", "CreditAmount");
    private final static QName _CustomerID_QNAME = new QName("", "CustomerID");
    private final static QName _ExportedMode_QNAME = new QName("", "ExportedMode");
    private final static QName _BrandName_QNAME = new QName("", "BrandName");
    private final static QName _ODLimit_QNAME = new QName("", "ODLimit");
    private final static QName _AccountStatus_QNAME = new QName("", "AccountStatus");
    private final static QName _PhoneNo_QNAME = new QName("", "PhoneNo");
    private final static QName _Currency_QNAME = new QName("", "Currency");
    private final static QName _ValueDate_QNAME = new QName("", "ValueDate");
    private final static QName _DebitCount_QNAME = new QName("", "DebitCount");
    private final static QName _CustomerName_QNAME = new QName("", "CustomerName");
    private final static QName _DepositAmount_QNAME = new QName("", "DepositAmount");
    private final static QName _AccountNo_QNAME = new QName("", "AccountNo");
    private final static QName _FirstName_QNAME = new QName("", "FirstName");
    private final static QName _IFSCCode_QNAME = new QName("", "IFSCCode");
    private final static QName _ReferenceNumber_QNAME = new QName("", "ReferenceNumber");
    private final static QName _Address2_QNAME = new QName("", "Address2");
    private final static QName _BankCode_QNAME = new QName("", "BankCode");
    private final static QName _Address1_QNAME = new QName("", "Address1");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _MiddleName_QNAME = new QName("", "MiddleName");
    private final static QName _Date_QNAME = new QName("", "Date");
    private final static QName _WithdrawalAmount_QNAME = new QName("", "WithdrawalAmount");
    private final static QName _ClosingBalance_QNAME = new QName("", "ClosingBalance");
    private final static QName _ExportedDate_QNAME = new QName("", "ExportedDate");
    private final static QName _BranchDetail_QNAME = new QName("", "BranchDetail");
    private final static QName _Region_QNAME = new QName("", "Region");
    private final static QName _Country_QNAME = new QName("", "Country");
    private final static QName _FromDate_QNAME = new QName("", "FromDate");
    private final static QName _ToDate_QNAME = new QName("", "ToDate");
    private final static QName _LastName_QNAME = new QName("", "LastName");
    private final static QName _PostCode_QNAME = new QName("", "PostCode");
    private final static QName _DebitAmount_QNAME = new QName("", "DebitAmount");
    private final static QName _BranchCode_QNAME = new QName("", "BranchCode");
    private final static QName _CreditCount_QNAME = new QName("", "CreditCount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.miles.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link StatementExport }
     * 
     */
    public StatementExport createStatementExport() {
        return new StatementExport();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Statements }
     * 
     */
    public Statements createStatements() {
        return new Statements();
    }

    /**
     * Create an instance of {@link Statement }
     * 
     */
    public Statement createStatement() {
        return new Statement();
    }

    /**
     * Create an instance of {@link Bank }
     * 
     */
    public Bank createBank() {
        return new Bank();
    }

    /**
     * Create an instance of {@link Branch }
     * 
     */
    public Branch createBranch() {
        return new Branch();
    }

    /**
     * Create an instance of {@link AccountDetails }
     * 
     */
    public AccountDetails createAccountDetails() {
        return new AccountDetails();
    }

    /**
     * Create an instance of {@link AccountStatement }
     * 
     */
    public AccountStatement createAccountStatement() {
        return new AccountStatement();
    }

    /**
     * Create an instance of {@link StatementLine }
     * 
     */
    public StatementLine createStatementLine() {
        return new StatementLine();
    }

    /**
     * Create an instance of {@link StatementSummary }
     * 
     */
    public StatementSummary createStatementSummary() {
        return new StatementSummary();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankName")
    public JAXBElement<String> createBankName(String value) {
        return new JAXBElement<String>(_BankName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MICRCode")
    public JAXBElement<Integer> createMICRCode(Integer value) {
        return new JAXBElement<Integer>(_MICRCode_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpeningBalance")
    public JAXBElement<String> createOpeningBalance(String value) {
        return new JAXBElement<String>(_OpeningBalance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumberOfRecords")
    public JAXBElement<Byte> createNumberOfRecords(Byte value) {
        return new JAXBElement<Byte>(_NumberOfRecords_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountOpenDate")
    public JAXBElement<String> createAccountOpenDate(String value) {
        return new JAXBElement<String>(_AccountOpenDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrandCode")
    public JAXBElement<String> createBrandCode(String value) {
        return new JAXBElement<String>(_BrandCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditAmount")
    public JAXBElement<Float> createCreditAmount(Float value) {
        return new JAXBElement<Float>(_CreditAmount_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerID")
    public JAXBElement<Integer> createCustomerID(Integer value) {
        return new JAXBElement<Integer>(_CustomerID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExportedMode")
    public JAXBElement<String> createExportedMode(String value) {
        return new JAXBElement<String>(_ExportedMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrandName")
    public JAXBElement<String> createBrandName(String value) {
        return new JAXBElement<String>(_BrandName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ODLimit")
    public JAXBElement<Float> createODLimit(Float value) {
        return new JAXBElement<Float>(_ODLimit_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountStatus")
    public JAXBElement<String> createAccountStatus(String value) {
        return new JAXBElement<String>(_AccountStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PhoneNo")
    public JAXBElement<Long> createPhoneNo(Long value) {
        return new JAXBElement<Long>(_PhoneNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValueDate")
    public JAXBElement<String> createValueDate(String value) {
        return new JAXBElement<String>(_ValueDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DebitCount")
    public JAXBElement<Byte> createDebitCount(Byte value) {
        return new JAXBElement<Byte>(_DebitCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DepositAmount")
    public JAXBElement<String> createDepositAmount(String value) {
        return new JAXBElement<String>(_DepositAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccountNo")
    public JAXBElement<Long> createAccountNo(Long value) {
        return new JAXBElement<Long>(_AccountNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IFSCCode")
    public JAXBElement<String> createIFSCCode(String value) {
        return new JAXBElement<String>(_IFSCCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferenceNumber")
    public JAXBElement<String> createReferenceNumber(String value) {
        return new JAXBElement<String>(_ReferenceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankCode")
    public JAXBElement<String> createBankCode(String value) {
        return new JAXBElement<String>(_BankCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MiddleName")
    public JAXBElement<String> createMiddleName(String value) {
        return new JAXBElement<String>(_MiddleName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WithdrawalAmount")
    public JAXBElement<String> createWithdrawalAmount(String value) {
        return new JAXBElement<String>(_WithdrawalAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClosingBalance")
    public JAXBElement<String> createClosingBalance(String value) {
        return new JAXBElement<String>(_ClosingBalance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExportedDate")
    public JAXBElement<String> createExportedDate(String value) {
        return new JAXBElement<String>(_ExportedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BranchDetail")
    public JAXBElement<String> createBranchDetail(String value) {
        return new JAXBElement<String>(_BranchDetail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromDate")
    public JAXBElement<String> createFromDate(String value) {
        return new JAXBElement<String>(_FromDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToDate")
    public JAXBElement<String> createToDate(String value) {
        return new JAXBElement<String>(_ToDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PostCode")
    public JAXBElement<Integer> createPostCode(Integer value) {
        return new JAXBElement<Integer>(_PostCode_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DebitAmount")
    public JAXBElement<String> createDebitAmount(String value) {
        return new JAXBElement<String>(_DebitAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BranchCode")
    public JAXBElement<Short> createBranchCode(Short value) {
        return new JAXBElement<Short>(_BranchCode_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditCount")
    public JAXBElement<Byte> createCreditCount(Byte value) {
        return new JAXBElement<Byte>(_CreditCount_QNAME, Byte.class, null, value);
    }

}
