//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ProdId"/&gt;
 *         &lt;element ref="{}Field1"/&gt;
 *         &lt;element ref="{}Field2"/&gt;
 *         &lt;element ref="{}Field3"/&gt;
 *         &lt;element ref="{}Field4"/&gt;
 *         &lt;element ref="{}Field5"/&gt;
 *         &lt;element ref="{}Field6"/&gt;
 *         &lt;element ref="{}Field7"/&gt;
 *         &lt;element ref="{}Field8"/&gt;
 *         &lt;element ref="{}Field9"/&gt;
 *         &lt;element ref="{}Field10"/&gt;
 *         &lt;element ref="{}Field11"/&gt;
 *         &lt;element ref="{}Field12"/&gt;
 *         &lt;element ref="{}Field13"/&gt;
 *         &lt;element ref="{}Field14"/&gt;
 *         &lt;element ref="{}Field15"/&gt;
 *         &lt;element ref="{}Field16"/&gt;
 *         &lt;element ref="{}Field17"/&gt;
 *         &lt;element ref="{}Field18"/&gt;
 *         &lt;element ref="{}Field19"/&gt;
 *         &lt;element ref="{}Field20"/&gt;
 *         &lt;element ref="{}Label1"/&gt;
 *         &lt;element ref="{}Label2"/&gt;
 *         &lt;element ref="{}Label3"/&gt;
 *         &lt;element ref="{}Label4"/&gt;
 *         &lt;element ref="{}Label5"/&gt;
 *         &lt;element ref="{}Label6"/&gt;
 *         &lt;element ref="{}Label7"/&gt;
 *         &lt;element ref="{}Label8"/&gt;
 *         &lt;element ref="{}Label9"/&gt;
 *         &lt;element ref="{}Label10"/&gt;
 *         &lt;element ref="{}Label11"/&gt;
 *         &lt;element ref="{}Label12"/&gt;
 *         &lt;element ref="{}Label13"/&gt;
 *         &lt;element ref="{}Label14"/&gt;
 *         &lt;element ref="{}Label15"/&gt;
 *         &lt;element ref="{}Label16"/&gt;
 *         &lt;element ref="{}Label17"/&gt;
 *         &lt;element ref="{}Label18"/&gt;
 *         &lt;element ref="{}Label19"/&gt;
 *         &lt;element ref="{}Label20"/&gt;
 *         &lt;element ref="{}Description"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prodId",
    "field1",
    "field2",
    "field3",
    "field4",
    "field5",
    "field6",
    "field7",
    "field8",
    "field9",
    "field10",
    "field11",
    "field12",
    "field13",
    "field14",
    "field15",
    "field16",
    "field17",
    "field18",
    "field19",
    "field20",
    "label1",
    "label2",
    "label3",
    "label4",
    "label5",
    "label6",
    "label7",
    "label8",
    "label9",
    "label10",
    "label11",
    "label12",
    "label13",
    "label14",
    "label15",
    "label16",
    "label17",
    "label18",
    "label19",
    "label20",
    "description",
    "serviceAgreeSerialNo"
})
@XmlRootElement(name = "ProductParameters-118")
public class ProductParameters118 {

    @XmlElement(name = "ProdId", required = true)
    protected String prodId;
    @XmlElement(name = "Field1")
    protected byte field1;
    @XmlElement(name = "Field2")
    protected byte field2;
    @XmlElement(name = "Field3")
    protected float field3;
    @XmlElement(name = "Field4")
    protected float field4;
    @XmlElement(name = "Field5")
    protected float field5;
    @XmlElement(name = "Field6")
    protected float field6;
    @XmlElement(name = "Field7")
    protected float field7;
    @XmlElement(name = "Field8")
    protected float field8;
    @XmlElement(name = "Field9")
    protected float field9;
    @XmlElement(name = "Field10")
    protected float field10;
    @XmlElement(name = "Field11")
    protected float field11;
    @XmlElement(name = "Field12")
    protected float field12;
    @XmlElement(name = "Field13")
    protected float field13;
    @XmlElement(name = "Field14")
    protected float field14;
    @XmlElement(name = "Field15")
    protected float field15;
    @XmlElement(name = "Field16")
    protected float field16;
    @XmlElement(name = "Field17")
    protected float field17;
    @XmlElement(name = "Field18")
    protected float field18;
    @XmlElement(name = "Field19")
    protected float field19;
    @XmlElement(name = "Field20")
    protected float field20;
    @XmlElement(name = "Label1", required = true)
    protected String label1;
    @XmlElement(name = "Label2", required = true)
    protected String label2;
    @XmlElement(name = "Label3", required = true)
    protected String label3;
    @XmlElement(name = "Label4", required = true)
    protected String label4;
    @XmlElement(name = "Label5", required = true)
    protected String label5;
    @XmlElement(name = "Label6", required = true)
    protected String label6;
    @XmlElement(name = "Label7", required = true)
    protected String label7;
    @XmlElement(name = "Label8", required = true)
    protected String label8;
    @XmlElement(name = "Label9", required = true)
    protected String label9;
    @XmlElement(name = "Label10", required = true)
    protected String label10;
    @XmlElement(name = "Label11", required = true)
    protected String label11;
    @XmlElement(name = "Label12", required = true)
    protected String label12;
    @XmlElement(name = "Label13", required = true)
    protected String label13;
    @XmlElement(name = "Label14", required = true)
    protected String label14;
    @XmlElement(name = "Label15", required = true)
    protected String label15;
    @XmlElement(name = "Label16", required = true)
    protected String label16;
    @XmlElement(name = "Label17", required = true)
    protected String label17;
    @XmlElement(name = "Label18", required = true)
    protected String label18;
    @XmlElement(name = "Label19", required = true)
    protected String label19;
    @XmlElement(name = "Label20", required = true)
    protected String label20;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;

    /**
     * Gets the value of the prodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * Sets the value of the prodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdId(String value) {
        this.prodId = value;
    }

    /**
     * Gets the value of the field1 property.
     * 
     */
    public byte getField1() {
        return field1;
    }

    /**
     * Sets the value of the field1 property.
     * 
     */
    public void setField1(byte value) {
        this.field1 = value;
    }

    /**
     * Gets the value of the field2 property.
     * 
     */
    public byte getField2() {
        return field2;
    }

    /**
     * Sets the value of the field2 property.
     * 
     */
    public void setField2(byte value) {
        this.field2 = value;
    }

    /**
     * Gets the value of the field3 property.
     * 
     */
    public float getField3() {
        return field3;
    }

    /**
     * Sets the value of the field3 property.
     * 
     */
    public void setField3(float value) {
        this.field3 = value;
    }

    /**
     * Gets the value of the field4 property.
     * 
     */
    public float getField4() {
        return field4;
    }

    /**
     * Sets the value of the field4 property.
     * 
     */
    public void setField4(float value) {
        this.field4 = value;
    }

    /**
     * Gets the value of the field5 property.
     * 
     */
    public float getField5() {
        return field5;
    }

    /**
     * Sets the value of the field5 property.
     * 
     */
    public void setField5(float value) {
        this.field5 = value;
    }

    /**
     * Gets the value of the field6 property.
     * 
     */
    public float getField6() {
        return field6;
    }

    /**
     * Sets the value of the field6 property.
     * 
     */
    public void setField6(float value) {
        this.field6 = value;
    }

    /**
     * Gets the value of the field7 property.
     * 
     */
    public float getField7() {
        return field7;
    }

    /**
     * Sets the value of the field7 property.
     * 
     */
    public void setField7(float value) {
        this.field7 = value;
    }

    /**
     * Gets the value of the field8 property.
     * 
     */
    public float getField8() {
        return field8;
    }

    /**
     * Sets the value of the field8 property.
     * 
     */
    public void setField8(float value) {
        this.field8 = value;
    }

    /**
     * Gets the value of the field9 property.
     * 
     */
    public float getField9() {
        return field9;
    }

    /**
     * Sets the value of the field9 property.
     * 
     */
    public void setField9(float value) {
        this.field9 = value;
    }

    /**
     * Gets the value of the field10 property.
     * 
     */
    public float getField10() {
        return field10;
    }

    /**
     * Sets the value of the field10 property.
     * 
     */
    public void setField10(float value) {
        this.field10 = value;
    }

    /**
     * Gets the value of the field11 property.
     * 
     */
    public float getField11() {
        return field11;
    }

    /**
     * Sets the value of the field11 property.
     * 
     */
    public void setField11(float value) {
        this.field11 = value;
    }

    /**
     * Gets the value of the field12 property.
     * 
     */
    public float getField12() {
        return field12;
    }

    /**
     * Sets the value of the field12 property.
     * 
     */
    public void setField12(float value) {
        this.field12 = value;
    }

    /**
     * Gets the value of the field13 property.
     * 
     */
    public float getField13() {
        return field13;
    }

    /**
     * Sets the value of the field13 property.
     * 
     */
    public void setField13(float value) {
        this.field13 = value;
    }

    /**
     * Gets the value of the field14 property.
     * 
     */
    public float getField14() {
        return field14;
    }

    /**
     * Sets the value of the field14 property.
     * 
     */
    public void setField14(float value) {
        this.field14 = value;
    }

    /**
     * Gets the value of the field15 property.
     * 
     */
    public float getField15() {
        return field15;
    }

    /**
     * Sets the value of the field15 property.
     * 
     */
    public void setField15(float value) {
        this.field15 = value;
    }

    /**
     * Gets the value of the field16 property.
     * 
     */
    public float getField16() {
        return field16;
    }

    /**
     * Sets the value of the field16 property.
     * 
     */
    public void setField16(float value) {
        this.field16 = value;
    }

    /**
     * Gets the value of the field17 property.
     * 
     */
    public float getField17() {
        return field17;
    }

    /**
     * Sets the value of the field17 property.
     * 
     */
    public void setField17(float value) {
        this.field17 = value;
    }

    /**
     * Gets the value of the field18 property.
     * 
     */
    public float getField18() {
        return field18;
    }

    /**
     * Sets the value of the field18 property.
     * 
     */
    public void setField18(float value) {
        this.field18 = value;
    }

    /**
     * Gets the value of the field19 property.
     * 
     */
    public float getField19() {
        return field19;
    }

    /**
     * Sets the value of the field19 property.
     * 
     */
    public void setField19(float value) {
        this.field19 = value;
    }

    /**
     * Gets the value of the field20 property.
     * 
     */
    public float getField20() {
        return field20;
    }

    /**
     * Sets the value of the field20 property.
     * 
     */
    public void setField20(float value) {
        this.field20 = value;
    }

    /**
     * Gets the value of the label1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * Sets the value of the label1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel1(String value) {
        this.label1 = value;
    }

    /**
     * Gets the value of the label2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel2() {
        return label2;
    }

    /**
     * Sets the value of the label2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel2(String value) {
        this.label2 = value;
    }

    /**
     * Gets the value of the label3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel3() {
        return label3;
    }

    /**
     * Sets the value of the label3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel3(String value) {
        this.label3 = value;
    }

    /**
     * Gets the value of the label4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel4() {
        return label4;
    }

    /**
     * Sets the value of the label4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel4(String value) {
        this.label4 = value;
    }

    /**
     * Gets the value of the label5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel5() {
        return label5;
    }

    /**
     * Sets the value of the label5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel5(String value) {
        this.label5 = value;
    }

    /**
     * Gets the value of the label6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel6() {
        return label6;
    }

    /**
     * Sets the value of the label6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel6(String value) {
        this.label6 = value;
    }

    /**
     * Gets the value of the label7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel7() {
        return label7;
    }

    /**
     * Sets the value of the label7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel7(String value) {
        this.label7 = value;
    }

    /**
     * Gets the value of the label8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel8() {
        return label8;
    }

    /**
     * Sets the value of the label8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel8(String value) {
        this.label8 = value;
    }

    /**
     * Gets the value of the label9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel9() {
        return label9;
    }

    /**
     * Sets the value of the label9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel9(String value) {
        this.label9 = value;
    }

    /**
     * Gets the value of the label10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel10() {
        return label10;
    }

    /**
     * Sets the value of the label10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel10(String value) {
        this.label10 = value;
    }

    /**
     * Gets the value of the label11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel11() {
        return label11;
    }

    /**
     * Sets the value of the label11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel11(String value) {
        this.label11 = value;
    }

    /**
     * Gets the value of the label12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel12() {
        return label12;
    }

    /**
     * Sets the value of the label12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel12(String value) {
        this.label12 = value;
    }

    /**
     * Gets the value of the label13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel13() {
        return label13;
    }

    /**
     * Sets the value of the label13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel13(String value) {
        this.label13 = value;
    }

    /**
     * Gets the value of the label14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel14() {
        return label14;
    }

    /**
     * Sets the value of the label14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel14(String value) {
        this.label14 = value;
    }

    /**
     * Gets the value of the label15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel15() {
        return label15;
    }

    /**
     * Sets the value of the label15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel15(String value) {
        this.label15 = value;
    }

    /**
     * Gets the value of the label16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel16() {
        return label16;
    }

    /**
     * Sets the value of the label16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel16(String value) {
        this.label16 = value;
    }

    /**
     * Gets the value of the label17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel17() {
        return label17;
    }

    /**
     * Sets the value of the label17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel17(String value) {
        this.label17 = value;
    }

    /**
     * Gets the value of the label18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel18() {
        return label18;
    }

    /**
     * Sets the value of the label18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel18(String value) {
        this.label18 = value;
    }

    /**
     * Gets the value of the label19 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel19() {
        return label19;
    }

    /**
     * Sets the value of the label19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel19(String value) {
        this.label19 = value;
    }

    /**
     * Gets the value of the label20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel20() {
        return label20;
    }

    /**
     * Sets the value of the label20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel20(String value) {
        this.label20 = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

}
