//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OpeningBalance"/>
 *         &lt;element ref="{}DebitCount"/>
 *         &lt;element ref="{}CreditCount"/>
 *         &lt;element ref="{}DebitAmount"/>
 *         &lt;element ref="{}CreditAmount"/>
 *         &lt;element ref="{}ClosingBalance"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "openingBalance",
    "debitCount",
    "creditCount",
    "debitAmount",
    "creditAmount",
    "closingBalance"
})
@XmlRootElement(name = "StatementSummary")
public class StatementSummary {

    @XmlElement(name = "OpeningBalance", required = true)
    protected String openingBalance;
    @XmlElement(name = "DebitCount")
    protected int debitCount;
    @XmlElement(name = "CreditCount")
    protected int creditCount;
    @XmlElement(name = "DebitAmount", required = true)
    protected String debitAmount;
    @XmlElement(name = "CreditAmount")
    protected float creditAmount;
    @XmlElement(name = "ClosingBalance", required = true)
    protected String closingBalance;

    /**
     * Gets the value of the openingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeningBalance() {
        return openingBalance;
    }

    /**
     * Sets the value of the openingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeningBalance(String value) {
        this.openingBalance = value;
    }

    /**
     * Gets the value of the debitCount property.
     * 
     */
    public int getDebitCount() {
        return debitCount;
    }

    /**
     * Sets the value of the debitCount property.
     * 
     */
    public void setDebitCount(int value) {
        this.debitCount = value;
    }

    /**
     * Gets the value of the creditCount property.
     * 
     */
    public int getCreditCount() {
        return creditCount;
    }

    /**
     * Sets the value of the creditCount property.
     * 
     */
    public void setCreditCount(int value) {
        this.creditCount = value;
    }

    /**
     * Gets the value of the debitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitAmount() {
        return debitAmount;
    }

    /**
     * Sets the value of the debitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitAmount(String value) {
        this.debitAmount = value;
    }

    /**
     * Gets the value of the creditAmount property.
     * 
     */
    public float getCreditAmount() {
        return creditAmount;
    }

    /**
     * Sets the value of the creditAmount property.
     * 
     */
    public void setCreditAmount(float value) {
        this.creditAmount = value;
    }

    /**
     * Gets the value of the closingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosingBalance() {
        return closingBalance;
    }

    /**
     * Sets the value of the closingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosingBalance(String value) {
        this.closingBalance = value;
    }

}
