//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:28:41 AM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Bank"/>
 *         &lt;element ref="{}Customer"/>
 *         &lt;element ref="{}AccountDetails"/>
 *         &lt;element ref="{}AccountStatement"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "bank",
    "customer",
    "accountDetails",
    "accountStatement",
        "pieChart",
        "barGraph"
})
@XmlRootElement(name = "Statement")
public class Statement {
    @XmlElement(name = "Header", required = true)
    protected Header header;

    @XmlElement(name = "Bank", required = true)
    protected Bank bank;
    @XmlElement(name = "Customer", required = true)
    protected Customer customer;
    @XmlElement(name = "AccountDetails", required = true)
    protected AccountDetails accountDetails;
    @XmlElement(name = "AccountStatement", required = true)
    protected AccountStatement accountStatement;
    @XmlElement(name="PieChart")
    protected PieChart pieChart;
    @XmlElement(name="BarGraph")
    protected BarGraph barGraph;
    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link Bank }
     *     
     */
    public Bank getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bank }
     *     
     */
    public void setBank(Bank value) {
        this.bank = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the accountDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetails }
     *     
     */
    public AccountDetails getAccountDetails() {
        return accountDetails;
    }

    /**
     * Sets the value of the accountDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetails }
     *     
     */
    public void setAccountDetails(AccountDetails value) {
        this.accountDetails = value;
    }

    /**
     * Gets the value of the accountStatement property.
     * 
     * @return
     *     possible object is
     *     {@link AccountStatement }
     *     
     */
    public AccountStatement getAccountStatement() {
        return accountStatement;
    }

    /**
     * Sets the value of the accountStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountStatement }
     *     
     */
    public void setAccountStatement(AccountStatement value) {
        this.accountStatement = value;
    }

    public BarGraph getBarGraph() {
        return barGraph;
    }

    public void setBarGraph(BarGraph barGraph) {
        this.barGraph = barGraph;
    }

    public PieChart getPieChart() {
        return pieChart;
    }

    public void setPieChart(PieChart pieChart) {
        this.pieChart = pieChart;
    }
}
