//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.12 at 05:23:10 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}VatPercent"/&gt;
 *         &lt;element ref="{}VatBaseAmount"/&gt;
 *         &lt;element ref="{}VatAmount"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vatPercent",
    "vatBaseAmount",
    "vatAmount"
})
@XmlRootElement(name = "VatInfo")
public class VatInfo {

    @XmlElement(name = "VatPercent")
    protected double vatPercent;
    @XmlElement(name = "VatBaseAmount")
    protected double vatBaseAmount;
    @XmlElement(name = "VatAmount")
    protected double vatAmount;

    /**
     * Gets the value of the vatPercent property.
     * 
     */
    public double getVatPercent() {
        return vatPercent;
    }

    /**
     * Sets the value of the vatPercent property.
     * 
     */
    public void setVatPercent(double value) {
        this.vatPercent = value;
    }

    /**
     * Gets the value of the vatBaseAmount property.
     * 
     */
    public double getVatBaseAmount() {
        return vatBaseAmount;
    }

    /**
     * Sets the value of the vatBaseAmount property.
     * 
     */
    public void setVatBaseAmount(double value) {
        this.vatBaseAmount = value;
    }

    /**
     * Gets the value of the vatAmount property.
     * 
     */
    public double getVatAmount() {
        return vatAmount;
    }

    /**
     * Sets the value of the vatAmount property.
     * 
     */
    public void setVatAmount(double value) {
        this.vatAmount = value;
    }

}
