package no.fjordkraft.im.if320.models;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2017.05.12 at 05:23:10 PM IST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType&gt;
*   &lt;complexContent&gt;
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
*       &lt;sequence&gt;
*         &lt;element ref="{}Invoice"/&gt;
*       &lt;/sequence&gt;
*     &lt;/restriction&gt;
*   &lt;/complexContent&gt;
* &lt;/complexType&gt;
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
/*@XmlType(name = "", propOrder = {
 "invoice"
})*/
@XmlRootElement(name = "VEDLEGG_EHF")
public class VEDLEGGEHF {

 @XmlElement(name = "Invoice", namespace = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" ,required = true)
 protected oasis.names.specification.ubl.schema.xsd.invoice_2.Invoice invoice;

public oasis.names.specification.ubl.schema.xsd.invoice_2.Invoice getInvoice() {
	return invoice;
}

public void setInvoice(oasis.names.specification.ubl.schema.xsd.invoice_2.Invoice invoice) {
	this.invoice = invoice;
}

 

}
