//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}AnnualConsumption"/&gt;
 *         &lt;element ref="{}B-AccountAmount"/&gt;
 *         &lt;element ref="{}PriceDate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annualConsumption",
    "bAccountAmount",
    "priceDate"
})
@XmlRootElement(name = "YearlyConsumption-123")
public class YearlyConsumption123 {

    @XmlElement(name = "AnnualConsumption")
    protected long annualConsumption;
    @XmlElement(name = "B-AccountAmount")
    protected double bAccountAmount;
    @XmlElement(name = "PriceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar priceDate;

    /**
     * Gets the value of the annualConsumption property.
     * 
     */
    public long getAnnualConsumption() {
        return annualConsumption;
    }

    /**
     * Sets the value of the annualConsumption property.
     * 
     */
    public void setAnnualConsumption(long value) {
        this.annualConsumption = value;
    }

    /**
     * Gets the value of the bAccountAmount property.
     * 
     */
    public double getBAccountAmount() {
        return bAccountAmount;
    }

    /**
     * Sets the value of the bAccountAmount property.
     * 
     */
    public void setBAccountAmount(double value) {
        this.bAccountAmount = value;
    }

    /**
     * Gets the value of the priceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPriceDate() {
        return priceDate;
    }

    /**
     * Sets the value of the priceDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPriceDate(XMLGregorianCalendar value) {
        this.priceDate = value;
    }

}
