--liquibase formatted sql
--changeset arpita:1 context:prod
---------------------Insert script for New BRAND : GEAS
Insert into IM_BRAND_CONFIG (ID,BRAND,USE_EA_BARCODE,AGREEMENT_NUMBER,SERVICELEVEL,PREFIX_KID,KONTONUMMER,DESCRIPTION,POSTCODE,CITY,NATIONALID,REGION,CREATED_TMS,UPDATED_TMS,CREATE_TIME,UPDATE_TIME) values (10,'GEAS','0','0706','6','236','15038671925','Midt Energi AS','57','Kjrkvollveien 1 ','7291','Stren',null,null,to_timestamp('22-OCT-18 01.47.02.438000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);



---------------------Insert script for New BRAND : DKAS
Insert into IM_BRAND_CONFIG (ID,BRAND,USE_EA_BARCODE,AGREEMENT_NUMBER,SERVICELEVEL,PREFIX_KID,KONTONUMMER,DESCRIPTION,POSTCODE,CITY,NATIONALID,REGION,CREATED_TMS,UPDATED_TMS,CREATE_TIME,UPDATE_TIME) values (11,'DKAS','0','0707','7','237','15038939251','Dragefossen AS','20','Osvegen 6 ','8251','Rognan',null,null,to_timestamp('22-OCT-18 01.51.32.295000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);

