Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (1,'Credit','Fakturagebyr bedrift Kredit','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (2,'Credit','Fakturagebyr privat Kredit','DI;Rabatt: Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (3,'Credit','Flatgebyr 3 bet fri månad','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (4,'Credit','Flatgebyr Rabatt','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (5,'Credit','Jevn strømregning, tre månedene gratis','DI;Jevn strømregning, gratis tre første måneder');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (6,'Debit','Fakturagebyr bedrift','DI;Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (7,'Debit','Fakturagebyr privat','DI;Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (8,'Debit','Flatgebyr','DI;Full kontroll');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (9,'Debit','Flatgebyr bedrift','DI;Jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (10,'Debit','Flatgebyr med bet fri månad','DI;Full kontroll, betalingsfri måned');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (11,'Credit','DI;Korrigering purregebyr','DI;Korrigering purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (12,'Credit','DI;Rabatt Min Bedrift','DI;Rabatt Min Bedrift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (13,'Credit','EK; Rabatt 100% fornøyd','DI; Rabatt 100% fornøyd');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (14,'Credit','EK; Rabatt fakturagebyr','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (15,'Credit','EK; Rabatt Gratis Strøm','DI; Rabatt Gratis Strøm');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (16,'Credit','EK; Rabatt Min bedrift','DI; Rabatt Min bedrift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (17,'Credit','EK; Rabatt purregebyr','DI; Rabatt purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (18,'Credit','EK; Rabatt purregebyr','DI; Rabatt purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (19,'Credit','EK;Annen kompensasjon','DI;Annen kompensasjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (20,'Credit','EK;Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (21,'Credit','EK;Kompensasjon bruddgebyr','DI; Kompensasjon bruddgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (22,'Credit','EK;Kompensasjon forsinket oppstart','DI; Kompensasjon forsinket oppstart');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (23,'Credit','EK;kompensasjon Kundefordel','DI; kompensasjon Kundefordel');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (24,'Credit','EK;Korrigering av strømpris','DI;Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (25,'Credit','EK;Rabatt 100% Fornøyd','DI;Rabatt 100% Fornøyd');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (26,'Credit','EK;Rabatt forsinkelsesrente','DI;Rabatt forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (27,'Credit','EK;Rabatt forsinkelsesrente','DI;Rabatt forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (28,'Credit','EK;Rabatt Trippelgaranti','DI;Rabatt Trippelgaranti');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (29,'Credit','EK;Rabatt Trumf Kampanje','DI;Rabatt Trumf Kampanje');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (30,'Credit','Fakturagebyr bedrift Kredit CHARGE','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (31,'Credit','Fakturagebyr privat Kredit CHARGE','DI;Rabatt: Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (32,'Credit','Flatgebyr creditering','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (33,'Credit','Flatgebyr Rabatt CHARGE','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (34,'Credit','Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (35,'Credit','Gebyr rabatt','DI;Rabatt Jevn Strømregning mars-april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (36,'Credit','Gebyr rabatt','DI;Rabatt Jevn Strømregning mars-april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (37,'Credit','Kjøp av kraftproduksjon','DI;Kjøp av kraftproduksjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (38,'Credit','Korrigering Flatgebyr','DI;Jevn strømregning korringering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (39,'Credit','MVA','DI;DI;MVA - h?y sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (40,'Credit','Purregebyr Kredinor','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (41,'Credit','Rabatt Administrasjonsgebyr','DI;Rabatt Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (42,'Credit','Refusjon Purregebyr / Morarenter','DI;Refusjon Purregebyr / Morarenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (43,'Credit','Tilbakeføring purregebyr CHARGE','DI;Tilbakeføring purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (44,'Credit','Tilbakeføring renter CHARGE','DI;Tilbakeføring renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (45,'Credit','Øresavrundning','DI;Øresavrundning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (46,'Debit','Administrasjonsgebyr','DI;Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (47,'Debit','EK;Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (48,'Debit','Flatgebyr','DI;Jevn strømregning mars');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (49,'Debit','Flatgebyr','DI;Jevn strømregning april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (50,'Debit','Flatgebyr','DI;Jevn strømregning mars-april');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (51,'Debit','FlatgebyrK','DI;Jevn strømregning K');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (52,'Debit','Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (53,'Debit','Garantert fornøyd Pluss','DI;Garantert fornøyd Pluss');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (54,'Debit','Korrigering av strømpris tilgodebeløp','DI; Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (55,'Debit','MVA','DI;DI;MVA - h?y sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (56,'Debit','Purregebyr','DI;Transaksjon fra påminnelse');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (57,'Debit','Purregebyr Kredinor','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (58,'Debit','Refusjon Purregebyr / Morarenter','DI;Refusjon Purregebyr / Morarenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (59,'Debit','Øresavrundning','DI;Øresavrundning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (60,'Debit','Purregebyr','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (61,'Debit','Purregebyr Kredinor','DI;Purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (62,'Credit','Omtvistet beløp','DI;Omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (63,'Credit','Omtvistet beløp','DI;Omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (64,'Debit','Omtvistet belöp','DI;Omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (65,'Debit','Tilbakefört omtvistet belöp','DI;Tilbakeført omtvistet beløp');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (66,'Credit','Fakturagebyr bedrift Kredit','DI;Rabatt Administrasjonsgebyr papir');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (67,'Credit','Fakturagebyr privat Kredit','DI;Rabatt: Papirfaktura');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (68,'Credit','Flatgebyr Rabatt','DI;Rabatt jevn strømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (69,'Credit','For mye innbetalt nettleie','DI;For mye innbetalt nettleie');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (70,'Credit','Overføring avbetalingskonto','DI;Avtalt beløp for avbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (71,'Credit','Overføring avbetalingskontoGA','DI;Overføring avbetalingskontoGA');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (72,'Credit','Overført grunnet feil innbetaling','DI;Overført innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (73,'Credit','Tilbakeføring purregebyr','DI;Tilbakeføring purregebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (74,'Credit','Tilbakeføring renter','DI;Tilbakeføring renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (75,'Credit','Tilbakeført Jevnstrømregning','DI;Tilbakeført Jevnstrømregning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (76,'Credit','Unspecified credit','DI;Overf¿¿rt tilgodebel¿¿p');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (77,'Debit','Administrajonsavgift','DI;Administrasjonsavgift');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (78,'Debit','EK;Tilbakefore kompensasjon','DI;Tilbakefore kompensasjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (79,'Debit','For lite innbetalt nettleie','DI;For lite innbetalt nettleie');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (80,'Debit','Korrigering av strømpris tilgodebeløp','DI; Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (81,'Debit','Korrigering av strømpris tilgodebeløp','DI; Korrigering strømpris');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (82,'Debit','Manuelt fakturagebyr','DI;Manuelt fakturagebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (83,'Debit','NedbetalingsordningGA','DI;Nedbetalingsordning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (84,'Debit','Negativ innbetaling','DI;Negativ innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (85,'Debit','Unspecified debit','DI;Overf¿¿rt skyldig bel¿¿p');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (86,'Debit','Ut grunnet feil innbetaling','DI;Korrigert innbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (87,'Credit','Opprettelse av avbetalingslösning','DI;Opprettelse av avbetalingsløsning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (88,'Debit','Opprettelse av avbetalingslösning','DI;Opprettelse av avbetalingsløsning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (89,'Credit','Overføring avbetalingskonto','DI;Avtalt beløp for avbetaling');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (90,'Debit','Nedbetalingsordning','DI;Nedbetalingsordning');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (91,'Credit','Renter tilgode','DI;Renter tilgode');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (92,'Debit','Avbetalingsrenter','DI;Avbetalingsrenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (93,'Debit','Forsinkelsesrente','DI;Forsinkelsesrente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (94,'Debit','Overtrekksrenter','DI;Overtrekksrenter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (95,'Debit','Skyldige renter','DI;Skyldige renter');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (96,'Credit','Intern kreditering','DI;Intern kreditering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (97,'Debit','Intern debitering','DI;Intern debitering');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (98,'Debit','Fradragsberettiget rente','DI;Fradragsberettiget rente');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (99,'Credit','Overföring','DI;Overføring til inkasso');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (100,'Credit','Overföring','DI;Overføring');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (101,'Debit','Overföring','DI;Overføring til inkasso');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (102,'Debit','Overföring','DI;Overføring');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (103,'Credit','Kjøp av kraftproduksjon','DI;Kjøp av kraftproduksjon');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (104,'Credit','Moms ekstern aktør','DI;Moms ekstern aktør');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (105,'Credit','MVA (avsetning tap)','DI;MVA (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (106,'Credit','MVA Credit','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (107,'Credit','MVA Credit','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (108,'Credit','MVA Credit','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (109,'Credit','MVA Flat - Credit','DI;MVA - Flat');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (110,'Credit','MVA Paper - Credit','DI;MVA - Paper');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (111,'Credit','MVA Rabatt Administrasjonsgebyr','DI;MVA Rabatt Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (112,'Debit','Moms ekstern aktør)','DI;Moms ekstern aktør');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (113,'Debit','MVA','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (114,'Debit','MVA','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (115,'Debit','MVA','DI;MVA - høy sats');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (116,'Debit','MVA Administrasjonsgebyr','DI;MVA Administrasjonsgebyr');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (117,'Debit','MVA Flat','DI;MVA - Flat');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (118,'Debit','MVA Paper','DI;MVA - Paper');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (119,'Credit','MVA (avsetning tap)','DI;MVA (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (120,'Credit','MVA Netteier (avsetning tap) Credit','DI;MVA netteier (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (121,'Debit','MVA (avsetning tap)','DI;MVA (avsetning tap)');
Insert into IM_TRANSACTION_CATEGORY (ID,TYPE,DESCRIPTION,CATEGORY) values (122,'Debit','MVA Netteier (avsetning tap)','DI;MVA netteier (avsetning tap)');