create table TRANSFERFILE
(
	TRANSFERTYPE VARCHAR2(20) not null,
	BRAND VARCHAR2(10) not null,
	FILENAME VARCHAR2(255) not null,
	CREATED TIMESTAMP(6),
	EKBATCHJOBID NUMBER,
	TRANSFERSTATUS VARCHAR2(20),
	STATUSUPDATED TIMESTAMP(6),
	FILESIZE NUMBER,
	TRANSFERREDBYTES NUMBER,
	FILESTORED TIMESTAMP(6),
	FILECONTENT CLOB,
	UPLOADSTARTED TIMESTAMP(6),
	UPLOADENDED TIMESTAMP(6),
	EHF NUMBER(1),
	COMPELLOUPLOADSTARTED TIMESTAMP(6),
	COMPELLOUPLOADENDED TIMESTAMP(6),
	constraint PK_TRANSFERFILE
		primary key (TRANSFERTYPE, BRAND, FILENAME)
)
/
