env: PROD
db_url: jdbc:oracle:oci:@P120
file_out_directory: /home/miles2/app/prod/im/output
liquibase_context: prod
liquibase_enable: enable
eureka_client_serviceUrl_defaultZone: http://fklx03.bkk.no:8761/eureka/
log_base_dir_path: /var/log
listOfServers_pdfgenerator: fklx14:9044
kafka_host: 1
kafka_port: 1

