---

-
  hosts: test-pdfgenerator
  remote_user: miles2
  vars:
    appfolderMap: {"im-ui":"InvoiceManagerUI","im-pdfgenerator":"PDFGenerator","im-preprocessor":"Preprocessor"}
  tasks:
    - include: stopapp.yml app=im-pdfgenerator

    - include: site.yml app=im-pdfgenerator


-
  hosts: test
  remote_user: miles2
  vars:
    appfolderMap: {"im-ui":"InvoiceManagerUI","im-pdfgenerator":"PDFGenerator","im-preprocessor":"Preprocessor"}
  tasks:
    - include: stopapp.yml app={{ line_item }}
      with_items:
        - im-ui
        - im-preprocessor
      loop_control:
        loop_var: line_item

    - include: site.yml app={{ item }}
      with_items:
        - im-ui
        - im-preprocessor

    - include: startapp.yml app={{ line_item2 }}
      with_items:
        - im-ui
        - im-preprocessor
      loop_control:
        loop_var: line_item2



