    -
      name: "Set the application folder"
      set_fact:
        appfolder: "{{appfolderMap[app]}}"
    -
      name: "{{app}}@{{inventory_hostname}} - Making sure base directory {{app_basedir}} exists"
      become: true
      file:
        path={{app_basedir}}
        state=directory
        owner=miles2

    -
      name: "{{app}}@{{inventory_hostname}} - Making sure directory {{app_basedir}}/{{app}} exists"
      become: true
      file:
        path={{app_basedir}}/{{app}}
        state=directory
        owner=miles2

    -
      name: "{{app}}@{{inventory_hostname}} - Making sure directory {{app_basedir}}/{{app}}/current exists"
      become: true
      file:
        path={{app_basedir}}/{{app}}/current
        state=directory
        owner=miles2
    -
      name: "{{app}}@{{inventory_hostname}} - Making sure directory {{app_basedir}}/{{app}}/previous exists"
      become: true
      file:
        path={{app_basedir}}/{{app}}/previous
        state=directory
        owner=miles2
    -
      name: "{{app}}@{{inventory_hostname}} - Making sure directory /var/log/invoicemanager/{{app}}/ exists"
      become: true
      file:
        path=/var/log/invoicemanager/{{app}}/
        state=directory
        owner=miles2

    -
      name: "{{app}}@{{inventory_hostname}} - Copying new binaries"
      copy:
        src="../{{appfolder}}/target/{{app}}.jar"
        dest="{{app_basedir}}/{{app}}/current/"
        mode=0700

    -
      name: "{{app}}@{{inventory_hostname}} - Copying config"
      template:
        src=templates/{{app}}/{{line_item}}
        dest={{app_basedir}}/{{app}}/current/{{line_item}}
        owner=miles2
      with_items:
        - application.yml
      loop_control:
        loop_var: line_item

    -
      name: "{{app}}@{{inventory_hostname}} - Copying obsidian properties"
      template:
        src=templates/{{app}}/com.carfey.properties
        dest={{app_basedir}}/{{app}}/current/{{line_item}}
        owner=miles2
      when: app == "im-preprocessor"


    -
      name: "{{app}}@{{inventory_hostname}} - Copying JVM config"
      template:
        src=templates//{{app}}/jvmconfig.conf
        dest="{{app_basedir}}/{{app}}/current/{{app}}-app.conf"
        owner=miles2