//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MainInvoiceInfo-101"/&gt;
 *         &lt;element ref="{}CustomerInfo-103"/&gt;
 *         &lt;element ref="{}InvoiceAgreementInfo-105"/&gt;
 *         &lt;element ref="{}Pass-ThroughInvoiceInfo-109"/&gt;
 *         &lt;element ref="{}InvoiceOrder"/&gt;
 *         &lt;element ref="{}VatSpecInvoice-142"/&gt;
 *         &lt;element ref="{}InvoiceEndRecord-199"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mainInvoiceInfo101",
    "customerInfo103",
    "invoiceAgreementInfo105",
    "passThroughInvoiceInfo109",
    "invoiceOrder",
    "vatSpecInvoice142",
    "invoiceEndRecord199",
    "messageTimestamp",
    "invoiceHeader",
    "invoiceDetails",
    "invoiceSummary"
})
@XmlRootElement(name = "Invoice")
public class Invoice {

    @XmlElement(name = "MainInvoiceInfo-101", required = true)
    protected MainInvoiceInfo101 mainInvoiceInfo101;
    @XmlElement(name = "CustomerInfo-103", required = true)
    protected CustomerInfo103 customerInfo103;
    @XmlElement(name = "InvoiceAgreementInfo-105", required = true)
    protected InvoiceAgreementInfo105 invoiceAgreementInfo105;
    @XmlElement(name = "Pass-ThroughInvoiceInfo-109", required = true)
    protected PassThroughInvoiceInfo109 passThroughInvoiceInfo109;
    @XmlElement(name = "InvoiceOrder", required = true)
    protected InvoiceOrder invoiceOrder;
    @XmlElement(name = "VatSpecInvoice-142", required = true)
    protected VatSpecInvoice142 vatSpecInvoice142;
    @XmlElement(name = "InvoiceEndRecord-199", required = true)
    protected InvoiceEndRecord199 invoiceEndRecord199;

    @XmlElement(name = "MessageTimestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar messageTimestamp;
    @XmlElement(name = "InvoiceHeader", required = true)
    protected InvoiceHeader invoiceHeader;
    @XmlElement(name = "InvoiceDetails", required = true)
    protected InvoiceDetails invoiceDetails;
    @XmlElement(name = "InvoiceSummary", required = true)
    protected InvoiceSummary invoiceSummary;
    @XmlAttribute(name = "MessageOwner")
    protected String messageOwner;
    @XmlAttribute(name = "MessageType")
    protected String messageType;
    @XmlAttribute(name = "MessageVersion")
    protected Float messageVersion;

    /**
     * Gets the value of the mainInvoiceInfo101 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.MainInvoiceInfo101 }
     *     
     */
    public MainInvoiceInfo101 getMainInvoiceInfo101() {
        return mainInvoiceInfo101;
    }

    /**
     * Sets the value of the mainInvoiceInfo101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.MainInvoiceInfo101 }
     *     
     */
    public void setMainInvoiceInfo101(MainInvoiceInfo101 value) {
        this.mainInvoiceInfo101 = value;
    }

    /**
     * Gets the value of the customerInfo103 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.CustomerInfo103 }
     *     
     */
    public CustomerInfo103 getCustomerInfo103() {
        return customerInfo103;
    }

    /**
     * Sets the value of the customerInfo103 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.CustomerInfo103 }
     *     
     */
    public void setCustomerInfo103(CustomerInfo103 value) {
        this.customerInfo103 = value;
    }

    /**
     * Gets the value of the invoiceAgreementInfo105 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceAgreementInfo105 }
     *     
     */
    public InvoiceAgreementInfo105 getInvoiceAgreementInfo105() {
        return invoiceAgreementInfo105;
    }

    /**
     * Sets the value of the invoiceAgreementInfo105 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceAgreementInfo105 }
     *     
     */
    public void setInvoiceAgreementInfo105(InvoiceAgreementInfo105 value) {
        this.invoiceAgreementInfo105 = value;
    }

    /**
     * Gets the value of the passThroughInvoiceInfo109 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.PassThroughInvoiceInfo109 }
     *     
     */
    public PassThroughInvoiceInfo109 getPassThroughInvoiceInfo109() {
        return passThroughInvoiceInfo109;
    }

    /**
     * Sets the value of the passThroughInvoiceInfo109 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.PassThroughInvoiceInfo109 }
     *     
     */
    public void setPassThroughInvoiceInfo109(PassThroughInvoiceInfo109 value) {
        this.passThroughInvoiceInfo109 = value;
    }

    /**
     * Gets the value of the invoiceOrder property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceOrder }
     *     
     */
    public InvoiceOrder getInvoiceOrder() {
        return invoiceOrder;
    }

    /**
     * Sets the value of the invoiceOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceOrder }
     *     
     */
    public void setInvoiceOrder(InvoiceOrder value) {
        this.invoiceOrder = value;
    }

    /**
     * Gets the value of the vatSpecInvoice142 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.VatSpecInvoice142 }
     *     
     */
    public VatSpecInvoice142 getVatSpecInvoice142() {
        return vatSpecInvoice142;
    }

    /**
     * Sets the value of the vatSpecInvoice142 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.VatSpecInvoice142 }
     *     
     */
    public void setVatSpecInvoice142(VatSpecInvoice142 value) {
        this.vatSpecInvoice142 = value;
    }

    /**
     * Gets the value of the invoiceEndRecord199 property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceEndRecord199 }
     *     
     */
    public InvoiceEndRecord199 getInvoiceEndRecord199() {
        return invoiceEndRecord199;
    }

    /**
     * Sets the value of the invoiceEndRecord199 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceEndRecord199 }
     *     
     */
    public void setInvoiceEndRecord199(InvoiceEndRecord199 value) {
        this.invoiceEndRecord199 = value;
    }

    /**
     * Gets the value of the messageTimestamp property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getMessageTimestamp() {
        return messageTimestamp;
    }

    /**
     * Sets the value of the messageTimestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public void setMessageTimestamp(XMLGregorianCalendar value) {
        this.messageTimestamp = value;
    }

    /**
     * Gets the value of the invoiceHeader property.
     *
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceHeader }
     *
     */
    public InvoiceHeader getInvoiceHeader() {
        return invoiceHeader;
    }

    /**
     * Sets the value of the invoiceHeader property.
     *
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceHeader }
     *
     */
    public void setInvoiceHeader(InvoiceHeader value) {
        this.invoiceHeader = value;
    }

    /**
     * Gets the value of the invoiceDetails property.
     *
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceDetails }
     *
     */
    public InvoiceDetails getInvoiceDetails() {
        return invoiceDetails;
    }

    /**
     * Sets the value of the invoiceDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceDetails }
     *
     */
    public void setInvoiceDetails(InvoiceDetails value) {
        this.invoiceDetails = value;
    }

    /**
     * Gets the value of the invoiceSummary property.
     *
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceSummary }
     *
     */
    public InvoiceSummary getInvoiceSummary() {
        return invoiceSummary;
    }

    /**
     * Sets the value of the invoiceSummary property.
     *
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.InvoiceSummary }
     *
     */
    public void setInvoiceSummary(InvoiceSummary value) {
        this.invoiceSummary = value;
    }

    /**
     * Gets the value of the messageOwner property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMessageOwner() {
        return messageOwner;
    }

    /**
     * Sets the value of the messageOwner property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMessageOwner(String value) {
        this.messageOwner = value;
    }

    /**
     * Gets the value of the messageType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageVersion property.
     *
     * @return
     *     possible object is
     *     {@link Float }
     *
     */
    public Float getMessageVersion() {
        return messageVersion;
    }

    /**
     * Sets the value of the messageVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link Float }
     *
     */
    public void setMessageVersion(Float value) {
        this.messageVersion = value;
    }

}
