//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}StartDate"/&gt;
 *         &lt;element ref="{}BillingGroup"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *         &lt;element ref="{}CloseCode"/&gt;
 *         &lt;element ref="{}TotalPrinted"/&gt;
 *         &lt;element ref="{}ShortTimeSA"/&gt;
 *         &lt;element ref="{}IndustryCode"/&gt;
 *         &lt;element ref="{}B-AccountCode"/&gt;
 *         &lt;element ref="{}InvoiceType"/&gt;
 *         &lt;element ref="{}ConsumptionCode"/&gt;
 *         &lt;element ref="{}AreaId"/&gt;
 *         &lt;element ref="{}LDC1"/&gt;
 *         &lt;element ref="{}LDC2"/&gt;
 *         &lt;element ref="{}Supplier1"/&gt;
 *         &lt;element ref="{}Supplier2"/&gt;
 *         &lt;element ref="{}B-AccountText"/&gt;
 *         &lt;element ref="{}Amount"/&gt;
 *         &lt;element ref="{}Instlmnt"/&gt;
 *         &lt;element ref="{}ActivityId"/&gt;
 *         &lt;element ref="{}ActivityType"/&gt;
 *         &lt;element ref="{}ActivitySubType"/&gt;
 *         &lt;element ref="{}ActivityName"/&gt;
 *         &lt;element ref="{}CompanyRegNo"/&gt;
 *         &lt;element ref="{}UtilityAccountNo"/&gt;
 *         &lt;element ref="{}ActivitySubTypeName"/&gt;
 *         &lt;element ref="{}YearEffect"/&gt;
 *         &lt;element ref="{}ActivityCloseable"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startDate",
    "billingGroup",
    "serviceAgreeSerialNo",
    "closeCode",
    "totalPrinted",
    "shortTimeSA",
    "industryCode",
    "bAccountCode",
    "invoiceType",
    "consumptionCode",
    "areaId",
    "ldc1",
    "ldc2",
    "supplier1",
    "supplier2",
    "bAccountText",
    "amount",
    "instlmnt",
    "activityId",
    "activityType",
    "activitySubType",
    "activityName",
    "companyRegNo",
    "utilityAccountNo",
    "activitySubTypeName",
    "yearEffect",
    "activityCloseable"
})
@XmlRootElement(name = "InvoiceOrderInfo-110")
public class InvoiceOrderInfo110 {

    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "BillingGroup", required = true)
    protected String billingGroup;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;
    @XmlElement(name = "CloseCode", required = true)
    protected String closeCode;
    @XmlElement(name = "TotalPrinted")
    protected float totalPrinted;
    @XmlElement(name = "ShortTimeSA", required = true)
    protected String shortTimeSA;
    @XmlElement(name = "IndustryCode", required = true)
    protected String industryCode;
    @XmlElement(name = "B-AccountCode", required = true)
    protected String bAccountCode;
    @XmlElement(name = "InvoiceType", required = true)
    protected String invoiceType;
    @XmlElement(name = "ConsumptionCode")
    protected byte consumptionCode;
    @XmlElement(name = "AreaId")
    protected short areaId;
    @XmlElement(name = "LDC1", required = true)
    protected String ldc1;
    @XmlElement(name = "LDC2", required = true)
    protected String ldc2;
    @XmlElement(name = "Supplier1", required = true)
    protected String supplier1;
    @XmlElement(name = "Supplier2", required = true)
    protected String supplier2;
    @XmlElement(name = "B-AccountText", required = true)
    protected String bAccountText;
    @XmlElement(name = "Amount")
    protected float amount;
    @XmlElement(name = "Instlmnt")
    protected byte instlmnt;
    @XmlElement(name = "ActivityId")
    protected byte activityId;
    @XmlElement(name = "ActivityType", required = true)
    protected String activityType;
    @XmlElement(name = "ActivitySubType", required = true)
    protected String activitySubType;
    @XmlElement(name = "ActivityName", required = true)
    protected String activityName;
    @XmlElement(name = "CompanyRegNo")
    protected int companyRegNo;
    @XmlElement(name = "UtilityAccountNo")
    protected long utilityAccountNo;
    @XmlElement(name = "ActivitySubTypeName", required = true)
    protected String activitySubTypeName;
    @XmlElement(name = "YearEffect")
    protected float yearEffect;
    @XmlElement(name = "ActivityCloseable", required = true)
    protected String activityCloseable;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the billingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingGroup() {
        return billingGroup;
    }

    /**
     * Sets the value of the billingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingGroup(String value) {
        this.billingGroup = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

    /**
     * Gets the value of the closeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseCode() {
        return closeCode;
    }

    /**
     * Sets the value of the closeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseCode(String value) {
        this.closeCode = value;
    }

    /**
     * Gets the value of the totalPrinted property.
     * 
     */
    public float getTotalPrinted() {
        return totalPrinted;
    }

    /**
     * Sets the value of the totalPrinted property.
     * 
     */
    public void setTotalPrinted(float value) {
        this.totalPrinted = value;
    }

    /**
     * Gets the value of the shortTimeSA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortTimeSA() {
        return shortTimeSA;
    }

    /**
     * Sets the value of the shortTimeSA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortTimeSA(String value) {
        this.shortTimeSA = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCode(String value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the bAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAccountCode() {
        return bAccountCode;
    }

    /**
     * Sets the value of the bAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAccountCode(String value) {
        this.bAccountCode = value;
    }

    /**
     * Gets the value of the invoiceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * Sets the value of the invoiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceType(String value) {
        this.invoiceType = value;
    }

    /**
     * Gets the value of the consumptionCode property.
     * 
     */
    public byte getConsumptionCode() {
        return consumptionCode;
    }

    /**
     * Sets the value of the consumptionCode property.
     * 
     */
    public void setConsumptionCode(byte value) {
        this.consumptionCode = value;
    }

    /**
     * Gets the value of the areaId property.
     * 
     */
    public short getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     */
    public void setAreaId(short value) {
        this.areaId = value;
    }

    /**
     * Gets the value of the ldc1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLDC1() {
        return ldc1;
    }

    /**
     * Sets the value of the ldc1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLDC1(String value) {
        this.ldc1 = value;
    }

    /**
     * Gets the value of the ldc2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLDC2() {
        return ldc2;
    }

    /**
     * Sets the value of the ldc2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLDC2(String value) {
        this.ldc2 = value;
    }

    /**
     * Gets the value of the supplier1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier1() {
        return supplier1;
    }

    /**
     * Sets the value of the supplier1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier1(String value) {
        this.supplier1 = value;
    }

    /**
     * Gets the value of the supplier2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier2() {
        return supplier2;
    }

    /**
     * Sets the value of the supplier2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier2(String value) {
        this.supplier2 = value;
    }

    /**
     * Gets the value of the bAccountText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAccountText() {
        return bAccountText;
    }

    /**
     * Sets the value of the bAccountText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAccountText(String value) {
        this.bAccountText = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public float getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(float value) {
        this.amount = value;
    }

    /**
     * Gets the value of the instlmnt property.
     * 
     */
    public byte getInstlmnt() {
        return instlmnt;
    }

    /**
     * Sets the value of the instlmnt property.
     * 
     */
    public void setInstlmnt(byte value) {
        this.instlmnt = value;
    }

    /**
     * Gets the value of the activityId property.
     * 
     */
    public byte getActivityId() {
        return activityId;
    }

    /**
     * Sets the value of the activityId property.
     * 
     */
    public void setActivityId(byte value) {
        this.activityId = value;
    }

    /**
     * Gets the value of the activityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * Sets the value of the activityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityType(String value) {
        this.activityType = value;
    }

    /**
     * Gets the value of the activitySubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivitySubType() {
        return activitySubType;
    }

    /**
     * Sets the value of the activitySubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivitySubType(String value) {
        this.activitySubType = value;
    }

    /**
     * Gets the value of the activityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * Sets the value of the activityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityName(String value) {
        this.activityName = value;
    }

    /**
     * Gets the value of the companyRegNo property.
     * 
     */
    public int getCompanyRegNo() {
        return companyRegNo;
    }

    /**
     * Sets the value of the companyRegNo property.
     * 
     */
    public void setCompanyRegNo(int value) {
        this.companyRegNo = value;
    }

    /**
     * Gets the value of the utilityAccountNo property.
     * 
     */
    public long getUtilityAccountNo() {
        return utilityAccountNo;
    }

    /**
     * Sets the value of the utilityAccountNo property.
     * 
     */
    public void setUtilityAccountNo(long value) {
        this.utilityAccountNo = value;
    }

    /**
     * Gets the value of the activitySubTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivitySubTypeName() {
        return activitySubTypeName;
    }

    /**
     * Sets the value of the activitySubTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivitySubTypeName(String value) {
        this.activitySubTypeName = value;
    }

    /**
     * Gets the value of the yearEffect property.
     * 
     */
    public float getYearEffect() {
        return yearEffect;
    }

    /**
     * Sets the value of the yearEffect property.
     * 
     */
    public void setYearEffect(float value) {
        this.yearEffect = value;
    }

    /**
     * Gets the value of the activityCloseable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityCloseable() {
        return activityCloseable;
    }

    /**
     * Sets the value of the activityCloseable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityCloseable(String value) {
        this.activityCloseable = value;
    }

}
