//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}InvoiceNo"/&gt;
 *         &lt;element ref="{}CustomerId"/&gt;
 *         &lt;element ref="{}CID"/&gt;
 *         &lt;element ref="{}PrintDate"/&gt;
 *         &lt;element ref="{}DueDate"/&gt;
 *         &lt;element ref="{}PayInst2Total"/&gt;
 *         &lt;element ref="{}PaymentDocNo"/&gt;
 *         &lt;element ref="{}GrossPresentation"/&gt;
 *         &lt;element ref="{}E-InvoiceTmpl"/&gt;
 *         &lt;element ref="{}StandingOrder"/&gt;
 *         &lt;element ref="{}ProcessCode"/&gt;
 *         &lt;element ref="{}FormTmplCode"/&gt;
 *         &lt;element ref="{}FormType"/&gt;
 *         &lt;element ref="{}DueDateDescription"/&gt;
 *         &lt;element ref="{}MoraInterest"/&gt;
 *         &lt;element ref="{}PrintedAmount"/&gt;
 *         &lt;element ref="{}PreviouslyPaid"/&gt;
 *         &lt;element ref="{}ToBePaid"/&gt;
 *         &lt;element ref="{}VAT"/&gt;
 *         &lt;element ref="{}TotPrintWithoutDec"/&gt;
 *         &lt;element ref="{}Decimals"/&gt;
 *         &lt;element ref="{}Mod10"/&gt;
 *         &lt;element ref="{}TotalOutstanding"/&gt;
 *         &lt;element ref="{}EInvoiceUrl"/&gt;
 *         &lt;element ref="{}Utility"/&gt;
 *         &lt;element ref="{}ReminderFee"/&gt;
 *         &lt;element ref="{}ToBePaidNet"/&gt;
 *         &lt;element ref="{}InvoiceDate"/&gt;
 *         &lt;element ref="{}CIDLong"/&gt;
 *         &lt;element ref="{}IsTestInvoice"/&gt;
 *         &lt;element ref="{}CreditedInvoiceNo"/&gt;
 *         &lt;element ref="{}E-InvoiceReferenceNew"/&gt;
 *         &lt;element ref="{}netPrintet"/&gt;
 *         &lt;element ref="{}RegulationRecords"/&gt;
 *         &lt;element ref="{}TemplateType"/&gt;
 *         &lt;element ref="{}Transactions"/&gt;
 *         &lt;element ref="{}Balance"/&gt;
 *         &lt;element ref="{}EInvoiceReferenceProposal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceNo",
    "customerId",
    "cid",
    "printDate",
    "dueDate",
    "payInst2Total",
    "paymentDocNo",
    "grossPresentation",
    "eInvoiceTmpl",
    "standingOrder",
    "processCode",
    "formTmplCode",
    "formType",
    "dueDateDescription",
    "moraInterest",
    "printedAmount",
    "previouslyPaid",
    "toBePaid",
    "vat",
    "totPrintWithoutDec",
    "decimals",
    "mod10",
    "totalOutstanding",
    "eInvoiceUrl",
    "utility",
    "reminderFee",
    "toBePaidNet",
    "invoiceDate",
    "cidLong",
    "isTestInvoice",
    "creditedInvoiceNo",
    "eInvoiceReferenceNew",
    "netPrintet",
    "regulationRecords",
    "templateType",
    "transactions",
    "balance",
    "eInvoiceReferenceProposal"
})
@XmlRootElement(name = "MainInvoiceInfo-101")
public class MainInvoiceInfo101 {

    @XmlElement(name = "InvoiceNo")
    protected int invoiceNo;
    @XmlElement(name = "CustomerId")
    protected int customerId;
    @XmlElement(name = "CID")
    protected long cid;
    @XmlElement(name = "PrintDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar printDate;
    @XmlElement(name = "DueDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "PayInst2Total")
    protected float payInst2Total;
    @XmlElement(name = "PaymentDocNo")
    protected byte paymentDocNo;
    @XmlElement(name = "GrossPresentation", required = true)
    protected String grossPresentation;
    @XmlElement(name = "E-InvoiceTmpl", required = true)
    protected String eInvoiceTmpl;
    @XmlElement(name = "StandingOrder")
    protected byte standingOrder;
    @XmlElement(name = "ProcessCode", required = true)
    protected String processCode;
    @XmlElement(name = "FormTmplCode", required = true)
    protected String formTmplCode;
    @XmlElement(name = "FormType", required = true)
    protected String formType;
    @XmlElement(name = "DueDateDescription", required = true)
    protected String dueDateDescription;
    @XmlElement(name = "MoraInterest")
    protected float moraInterest;
    @XmlElement(name = "PrintedAmount")
    protected float printedAmount;
    @XmlElement(name = "PreviouslyPaid")
    protected float previouslyPaid;
    @XmlElement(name = "ToBePaid")
    protected float toBePaid;
    @XmlElement(name = "VAT")
    protected float vat;
    @XmlElement(name = "TotPrintWithoutDec")
    protected short totPrintWithoutDec;
    @XmlElement(name = "Decimals")
    protected byte decimals;
    @XmlElement(name = "Mod10")
    protected byte mod10;
    @XmlElement(name = "TotalOutstanding")
    protected float totalOutstanding;
    @XmlElement(name = "EInvoiceUrl", required = true)
    protected String eInvoiceUrl;
    @XmlElement(name = "Utility", required = true)
    protected String utility;
    @XmlElement(name = "ReminderFee")
    protected float reminderFee;
    @XmlElement(name = "ToBePaidNet")
    protected float toBePaidNet;
    @XmlElement(name = "InvoiceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "CIDLong")
    protected long cidLong;
    @XmlElement(name = "IsTestInvoice", required = true)
    protected String isTestInvoice;
    @XmlElement(name = "CreditedInvoiceNo")
    protected byte creditedInvoiceNo;
    @XmlElement(name = "E-InvoiceReferenceNew")
    protected long eInvoiceReferenceNew;
    protected float netPrintet;
    @XmlElement(name = "RegulationRecords")
    protected float regulationRecords;
    @XmlElement(name = "TemplateType", required = true)
    protected String templateType;
    @XmlElement(name = "Transactions", required = true)
    protected Transactions transactions;
    @XmlElement(name = "Balance")
    protected float balance;
    @XmlElement(name = "EInvoiceReferenceProposal")
    protected long eInvoiceReferenceProposal;

    /**
     * Gets the value of the invoiceNo property.
     * 
     */
    public int getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * Sets the value of the invoiceNo property.
     * 
     */
    public void setInvoiceNo(int value) {
        this.invoiceNo = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     */
    public void setCustomerId(int value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the cid property.
     * 
     */
    public long getCID() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     * 
     */
    public void setCID(long value) {
        this.cid = value;
    }

    /**
     * Gets the value of the printDate property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrintDate() {
        return printDate;
    }

    /**
     * Sets the value of the printDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setPrintDate(XMLGregorianCalendar value) {
        this.printDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the payInst2Total property.
     * 
     */
    public float getPayInst2Total() {
        return payInst2Total;
    }

    /**
     * Sets the value of the payInst2Total property.
     * 
     */
    public void setPayInst2Total(float value) {
        this.payInst2Total = value;
    }

    /**
     * Gets the value of the paymentDocNo property.
     * 
     */
    public byte getPaymentDocNo() {
        return paymentDocNo;
    }

    /**
     * Sets the value of the paymentDocNo property.
     * 
     */
    public void setPaymentDocNo(byte value) {
        this.paymentDocNo = value;
    }

    /**
     * Gets the value of the grossPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossPresentation() {
        return grossPresentation;
    }

    /**
     * Sets the value of the grossPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossPresentation(String value) {
        this.grossPresentation = value;
    }

    /**
     * Gets the value of the eInvoiceTmpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEInvoiceTmpl() {
        return eInvoiceTmpl;
    }

    /**
     * Sets the value of the eInvoiceTmpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEInvoiceTmpl(String value) {
        this.eInvoiceTmpl = value;
    }

    /**
     * Gets the value of the standingOrder property.
     * 
     */
    public byte getStandingOrder() {
        return standingOrder;
    }

    /**
     * Sets the value of the standingOrder property.
     * 
     */
    public void setStandingOrder(byte value) {
        this.standingOrder = value;
    }

    /**
     * Gets the value of the processCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessCode() {
        return processCode;
    }

    /**
     * Sets the value of the processCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessCode(String value) {
        this.processCode = value;
    }

    /**
     * Gets the value of the formTmplCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormTmplCode() {
        return formTmplCode;
    }

    /**
     * Sets the value of the formTmplCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormTmplCode(String value) {
        this.formTmplCode = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    /**
     * Gets the value of the dueDateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDateDescription() {
        return dueDateDescription;
    }

    /**
     * Sets the value of the dueDateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDateDescription(String value) {
        this.dueDateDescription = value;
    }

    /**
     * Gets the value of the moraInterest property.
     * 
     */
    public float getMoraInterest() {
        return moraInterest;
    }

    /**
     * Sets the value of the moraInterest property.
     * 
     */
    public void setMoraInterest(float value) {
        this.moraInterest = value;
    }

    /**
     * Gets the value of the printedAmount property.
     * 
     */
    public float getPrintedAmount() {
        return printedAmount;
    }

    /**
     * Sets the value of the printedAmount property.
     * 
     */
    public void setPrintedAmount(float value) {
        this.printedAmount = value;
    }

    /**
     * Gets the value of the previouslyPaid property.
     * 
     */
    public float getPreviouslyPaid() {
        return previouslyPaid;
    }

    /**
     * Sets the value of the previouslyPaid property.
     * 
     */
    public void setPreviouslyPaid(float value) {
        this.previouslyPaid = value;
    }

    /**
     * Gets the value of the toBePaid property.
     * 
     */
    public float getToBePaid() {
        return toBePaid;
    }

    /**
     * Sets the value of the toBePaid property.
     * 
     */
    public void setToBePaid(float value) {
        this.toBePaid = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     */
    public float getVAT() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     */
    public void setVAT(float value) {
        this.vat = value;
    }

    /**
     * Gets the value of the totPrintWithoutDec property.
     * 
     */
    public short getTotPrintWithoutDec() {
        return totPrintWithoutDec;
    }

    /**
     * Sets the value of the totPrintWithoutDec property.
     * 
     */
    public void setTotPrintWithoutDec(short value) {
        this.totPrintWithoutDec = value;
    }

    /**
     * Gets the value of the decimals property.
     * 
     */
    public byte getDecimals() {
        return decimals;
    }

    /**
     * Sets the value of the decimals property.
     * 
     */
    public void setDecimals(byte value) {
        this.decimals = value;
    }

    /**
     * Gets the value of the mod10 property.
     * 
     */
    public byte getMod10() {
        return mod10;
    }

    /**
     * Sets the value of the mod10 property.
     * 
     */
    public void setMod10(byte value) {
        this.mod10 = value;
    }

    /**
     * Gets the value of the totalOutstanding property.
     * 
     */
    public float getTotalOutstanding() {
        return totalOutstanding;
    }

    /**
     * Sets the value of the totalOutstanding property.
     * 
     */
    public void setTotalOutstanding(float value) {
        this.totalOutstanding = value;
    }

    /**
     * Gets the value of the eInvoiceUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEInvoiceUrl() {
        return eInvoiceUrl;
    }

    /**
     * Sets the value of the eInvoiceUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEInvoiceUrl(String value) {
        this.eInvoiceUrl = value;
    }

    /**
     * Gets the value of the utility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtility() {
        return utility;
    }

    /**
     * Sets the value of the utility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtility(String value) {
        this.utility = value;
    }

    /**
     * Gets the value of the reminderFee property.
     * 
     */
    public float getReminderFee() {
        return reminderFee;
    }

    /**
     * Sets the value of the reminderFee property.
     * 
     */
    public void setReminderFee(float value) {
        this.reminderFee = value;
    }

    /**
     * Gets the value of the toBePaidNet property.
     * 
     */
    public float getToBePaidNet() {
        return toBePaidNet;
    }

    /**
     * Sets the value of the toBePaidNet property.
     * 
     */
    public void setToBePaidNet(float value) {
        this.toBePaidNet = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the cidLong property.
     * 
     */
    public long getCIDLong() {
        return cidLong;
    }

    /**
     * Sets the value of the cidLong property.
     * 
     */
    public void setCIDLong(long value) {
        this.cidLong = value;
    }

    /**
     * Gets the value of the isTestInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTestInvoice() {
        return isTestInvoice;
    }

    /**
     * Sets the value of the isTestInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTestInvoice(String value) {
        this.isTestInvoice = value;
    }

    /**
     * Gets the value of the creditedInvoiceNo property.
     * 
     */
    public byte getCreditedInvoiceNo() {
        return creditedInvoiceNo;
    }

    /**
     * Sets the value of the creditedInvoiceNo property.
     * 
     */
    public void setCreditedInvoiceNo(byte value) {
        this.creditedInvoiceNo = value;
    }

    /**
     * Gets the value of the eInvoiceReferenceNew property.
     * 
     */
    public long getEInvoiceReferenceNew() {
        return eInvoiceReferenceNew;
    }

    /**
     * Sets the value of the eInvoiceReferenceNew property.
     * 
     */
    public void setEInvoiceReferenceNew(long value) {
        this.eInvoiceReferenceNew = value;
    }

    /**
     * Gets the value of the netPrintet property.
     * 
     */
    public float getNetPrintet() {
        return netPrintet;
    }

    /**
     * Sets the value of the netPrintet property.
     * 
     */
    public void setNetPrintet(float value) {
        this.netPrintet = value;
    }

    /**
     * Gets the value of the regulationRecords property.
     * 
     */
    public float getRegulationRecords() {
        return regulationRecords;
    }

    /**
     * Sets the value of the regulationRecords property.
     * 
     */
    public void setRegulationRecords(float value) {
        this.regulationRecords = value;
    }

    /**
     * Gets the value of the templateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * Sets the value of the templateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateType(String value) {
        this.templateType = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link no.fjordkraft.im.if320.models.Transactions }
     *     
     */
    public Transactions getTransactions() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.fjordkraft.im.if320.models.Transactions }
     *     
     */
    public void setTransactions(Transactions value) {
        this.transactions = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     */
    public float getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     */
    public void setBalance(float value) {
        this.balance = value;
    }

    /**
     * Gets the value of the eInvoiceReferenceProposal property.
     * 
     */
    public long getEInvoiceReferenceProposal() {
        return eInvoiceReferenceProposal;
    }

    /**
     * Sets the value of the eInvoiceReferenceProposal property.
     * 
     */
    public void setEInvoiceReferenceProposal(long value) {
        this.eInvoiceReferenceProposal = value;
    }

}
