//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FirstInvoice"/&gt;
 *         &lt;element ref="{}ExtCustRef"/&gt;
 *         &lt;element ref="{}ToDate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firstInvoice",
    "extCustRef",
    "toDate"
})
@XmlRootElement(name = "Pass-ThroughInvoiceInfo-109")
public class PassThroughInvoiceInfo109 {

    @XmlElement(name = "FirstInvoice")
    protected byte firstInvoice;
    @XmlElement(name = "ExtCustRef", required = true)
    protected String extCustRef;
    @XmlElement(name = "ToDate", required = true)
    protected String toDate;

    /**
     * Gets the value of the firstInvoice property.
     * 
     */
    public byte getFirstInvoice() {
        return firstInvoice;
    }

    /**
     * Sets the value of the firstInvoice property.
     * 
     */
    public void setFirstInvoice(byte value) {
        this.firstInvoice = value;
    }

    /**
     * Gets the value of the extCustRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtCustRef() {
        return extCustRef;
    }

    /**
     * Sets the value of the extCustRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtCustRef(String value) {
        this.extCustRef = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(String value) {
        this.toDate = value;
    }

}
