//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.02 at 07:13:02 PM IST 
//


package no.fjordkraft.im.if320.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}StatisticCode"/&gt;
 *         &lt;element ref="{}Gross"/&gt;
 *         &lt;element ref="{}PriceCode"/&gt;
 *         &lt;element ref="{}Description"/&gt;
 *         &lt;element ref="{}Designation"/&gt;
 *         &lt;element ref="{}PriceDate"/&gt;
 *         &lt;element ref="{}Gross_high_precision"/&gt;
 *         &lt;element ref="{}ServiceAgreeSerialNo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statisticCode",
    "gross",
    "priceCode",
    "description",
    "designation",
    "priceDate",
    "grossHighPrecision",
    "serviceAgreeSerialNo"
})
@XmlRootElement(name = "PriceInfo-116")
public class PriceInfo116 {

    @XmlElement(name = "StatisticCode", required = true)
    protected String statisticCode;
    @XmlElement(name = "Gross")
    protected float gross;
    @XmlElement(name = "PriceCode", required = true)
    protected String priceCode;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Designation", required = true)
    protected String designation;
    @XmlElement(name = "PriceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar priceDate;
    @XmlElement(name = "Gross_high_precision")
    protected float grossHighPrecision;
    @XmlElement(name = "ServiceAgreeSerialNo")
    protected byte serviceAgreeSerialNo;

    /**
     * Gets the value of the statisticCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticCode() {
        return statisticCode;
    }

    /**
     * Sets the value of the statisticCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticCode(String value) {
        this.statisticCode = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     */
    public float getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     */
    public void setGross(float value) {
        this.gross = value;
    }

    /**
     * Gets the value of the priceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceCode() {
        return priceCode;
    }

    /**
     * Sets the value of the priceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceCode(String value) {
        this.priceCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the designation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * Sets the value of the designation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignation(String value) {
        this.designation = value;
    }

    /**
     * Gets the value of the priceDate property.
     * 
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPriceDate() {
        return priceDate;
    }

    /**
     * Sets the value of the priceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setPriceDate(XMLGregorianCalendar value) {
        this.priceDate = value;
    }

    /**
     * Gets the value of the grossHighPrecision property.
     * 
     */
    public float getGrossHighPrecision() {
        return grossHighPrecision;
    }

    /**
     * Sets the value of the grossHighPrecision property.
     * 
     */
    public void setGrossHighPrecision(float value) {
        this.grossHighPrecision = value;
    }

    /**
     * Gets the value of the serviceAgreeSerialNo property.
     * 
     */
    public byte getServiceAgreeSerialNo() {
        return serviceAgreeSerialNo;
    }

    /**
     * Sets the value of the serviceAgreeSerialNo property.
     * 
     */
    public void setServiceAgreeSerialNo(byte value) {
        this.serviceAgreeSerialNo = value;
    }

}
