env: TEST
db_url: jdbc:oracle:oci:@T120
eureka_client_serviceUrl_defaultZone: http://fk-t-lx03.bkk.no:8761/eureka/
log_base_dir_path: /var/log
newrelic_licence_key: "2480c11c71536a6c1cb7371e28adea750e3cf267cc446a8"