server:
  port: 8804
  contextPath: /invoicemanager

spring:
  #datasource:
  #  driverClassName: oracle.jdbc.driver.OracleDriver
  #  url: jdbc:oracle:thin:@imdb.cg8njogholnt.eu-central-1.rds.amazonaws.com:1521:orcl
  #  username: miles
  #  password: miles123

  datasource:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: bhavik
      password: bhavik123

logging:
  level:
    org.springframework.web: ERROR
    no.fjordkraft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #file: /opt/app/invoice_manager/logs/application.log
  file: D:\FuelKraft\invoice_manager\logs\im-ui.log

if320.skip.bytes: false
spring.jackson.serialization.fail-on-empty-beans: false


#  context: dev
#  enabled: disable


eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: true
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    preferIpAddress: true
    metadataMap:
      management:
        context-path: ${management.context-path}


ribbon:
  eureka:
    enabled: true