server:
  port: 8002

spring:
  main:
    banner-mode: 'off'
  profiles.active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: bhavik
    password: bhavik123
  application:
      name: invoicemanager

  #  datasource:
  #   driverClassName: oracle.jdbc.driver.OracleDriver
  #    url: jdbc:oracle:thin:@imdb.cg8njogholnt.eu-central-1.rds.amazonaws.com:1521:orcl
  #    username: miles
  #    password: miles123

logging:
  level:
    org.springframework.web: ERROR
    no.fjordkraft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /opt/app/invoice_manager/logs/application.log
  #file: D:\FuelKraft\invoice_manager\logs\application.log

